== African Empires

[quote.epigraph, Ghanaian Proverb]

  An army of sheep led by a lion can defeat an army of lions led by a sheep.


=== West Africa

==== Ghana

The **Ghana Empire** (Wagadou) ruled from about 300 to 1235.
It was founded by the Soninke people.
Notably, it placed value on gold, treating all gold nuggets as the king's property.
The name of the Ghana Empire referred to the ruler, who lived in Kumbi Saleh.

Important kings of the Ghana Empire included **Tunka Menin**.
It is said that the empire had 22 Muslim kings and 22 non-Muslim kings.
Kings used to perform a "`trial by wood`",
which involved giving an accused person a bitter piece of wood and seeing if he vomited.
We know about Ghana because of Al-Bakri's __Book of Highways and Empires__.

Ghana's decline led to the rise of the Sosso Empire.

==== Ashanti

The **Oyoko** clan settled at Kumasi and established the Ashanti Empire around the Ghana area.
The kings of the Ashanti Empire ruled from the great and divine throne
known as the **Golden Stool**.
The Stool reportedly descended from the heavens and landed on the first king, Osei Tutu.
Independence was declared in 1670.

==== Mali

The **Mali Empire** was founded in 1230 by **Sundiata** Keita,
who defeated Sumanguru (Soumaoro) of the Sosso Empire.
The Epic of Sundiata chronicles (semi-historically), the founding of the empire.
Sundiata's mother was the hunchback Sogolon.
He was born a cripple, ugly and lazy,
but then he lifted himself up using an iron rod,
bending it and resulting in "`The Hymn of the Bow`".
Mali would become well known for its overabundance of wealth.
Mali's capital was at **Timbuktu**.

The other important king of the Mali Empire was **Mansa Musa** (Musa I).
He once caused rampant inflation when he spent a lot of gold for salt in a pilgrimage to Mecca.
His general was Sagmandia, who recaptured Gao.
He also constructed the Sankore Madrasah (university) and the Djinguereber Mosque,
and employed architects such as Abu Ishaq as-Sahili.
Mansa Musa was notably shown in the Catalan Atlas holding a fleur-de-lis.

==== Songhai

The **Songhai Empire** succeeded the Mali Empire.
It was founded by **Sunni Ali** in 1464, and it would last until the late 1500s.
The capital was at **Gao**, but other major cities did include Timbuktu.
Notable locations included salt mines at Tagharza.

The empire was at its peak during the reign of **Askia Muhammad**.
Other important rulers include Kings Nuhu and Kossoi.

In the late 16th century, Morocco invaded the Songhai Empire.
Morocco was led by Judar Pasha against the Songhai King Askia Ishaq II.
The final confrontation occurred at the **Battle of Tondibi**.
The Songhai came up with the brilliant plan of sending a thousand cattle at the Moroccan lines.
Moroccan cannons sent the cattle stampeding right back at the Songhai,
breaking their lines and forcing them into retreat.
Judar Pasha moved on, sacking Gao and continuing to Timbuktu.

Despite the shattering of the Songhai Empire itself,
Morocco was never able to exert real influence over the area.
Many smaller states sprung up in the aftermath.
The Songhai reestablished themselves as the **Dendi Kingdom** by 1600,
a nation which would remain until it fell to the French in 1901.

=== South Africa

==== Great Zimbabwe

During the Iron Age, **Great Zimbabwe** was the capital of the Kingdom of Zimbabwe.
The city was constructed in the 11th century by Shona people,
and it stayed around until the 15th century.
The city included the Imba Huru (Great Enclosure) and it was excavated by Richard Hall.

The Shona constructed the Kingdom of Mutapa, which went between the Zambezi and Limpopo rivers.
I wish I had more to say on the subject, but I don't right now...
