== The Sundering of Europe

[quote.epigraph, Charlemagne]

  Would that I had twelve clerks so learned in all wisdom and so perfectly trained as were Jerome and Augustine.


=== The Fall of Rome

==== Destruction of the West

By the fourth century, Rome's influence in the Western world was unparalleled.
The empire had conquered much of the known world by the time of Constantine,
and even though it was split into multiple parts, it held quite a bit of sway
in Europe and in Northern Africa.
The fall of the Western Roman Empire in the fifth century was a big turning point in history.

In 378, the Goths were invading the Roman empire (they were running from the Huns),
and the Roman emperor **Valens** fought them at the **Battle of Adrianople**.
Prior to the battle, Valens had given the **Visigoths** the status of __foederati__,
and let them live across the Danube.
They had even helped the Romans fight the Huns.
But now, the invading army was comprised of:
the Thervings (Visigoths), led by Fritigern;
Bacurius the Iberian;
and the Greutungs, led by Alatheus and Saphrax.
Valens died at the battle (a result of being abandoned by his guards),
and **Gratian** came to power as a result.
The Goths' decisive victory struck a resounding blow against the might of the Romans;
Adrianople is often considered the beginning of the fall of western Rome,
despite the actual battle being fought by soldiers in the Eastern Roman Empire.

Gratian's reign ended in 383 when Magnus Maximus, emperor in the West, attacked Gaul and killed him.
**Theodosius I** became emperor.
Theodosius fought civil wars with the West,
and when he defeated Maximus, he appointed Valentinian II as Augustus in the West.

During the reign of Theodosius, a half-Vandal Roman general named **Stilicho**
was appointed guardian of the young future emperor Honorius.
**Alaric I** of the Balti dynasty became the leader of the **Visigoths**
(the Thervings of Adrianople)
after the death of Fritigern.
The Visigoths had separated from the Ostrogoths, who had gone their own way.
Alaric tried to rebel a couple times, but Stilicho stopped him.
Eventually Stilicho made peace with Alaric,
who went and joined the Romans and was no longer considered an enemy.

In 410, Stilicho was disgraced (a victim of conspiracy), hunted down, and killed.
Alaric was once again an enemy of the state, so he went on the offensive.
At this point, Rome wasn't the capital of the Western Roman Empire anymore
(that title had been given to Ravenna),
but it was still considered an eternal city, and it was still a focal point of the empire.

Rome itself hadn't been touched by any enemy since Brennus sacked it in 387 BC.
First, Alaric invaded Greece, killing many and wiping out the Eleusinian Mysteries.
Alaric invaded Italy and besieged Rome, trying to negotiate three times.
On the third siege, Alaric got fed up and entered the city,
pillaging and ransacking a lot of the big important buildings,
but on the whole, not causing a particularly massive amount of damage.
The sacking prompted **St. Augustine** to write __City of God__.
Augustine would later die during the Vandal siege.

Meanwhile, elsewhere in the empire, Honorius's lands were breaking.
Constantine III, last of the imperial usurpers,
managed to raise an army in Britain and march on Gaul.
He defeated Sarus (who was loyal to Honorius), and co-ruled with Honorius for a while.
The Visigoths went west from Italy, and ruled Spain from their capital at Toledo.
The Vandals eventually settled in the south of Spain.
Other barbarian tribes settled into parts of Spain and Gaul, splitting the empire even further.

In 444, the Huns were united by **Attila** (the "`Scourge of God`"),
who also included many Germanic tribes in his subjects.
Attila had taken the kingship after his brother Bleda had died.
He kept attacking the Eastern empire until 450, making money,
but he always stopped at the walls of Constantinople.
He then claimed the Emperor's sister Honoria as his wife,
and he invaded Gaul in 451 to get his "`dowry`", half of the Western Roman Empire.
The invasion was stopped by Flavius Aetius and the Visigoths
under Ostrogoth king **Theodoric the Great**
at battles at the **Catalunian Plains** and at **Chalons**.
Allegedly, Pope Leo I convinced Attila not to attack Rome --
soon after, Attila died of a nosebleed in his sleep.

By 439, the Vandals had crossed the Strait of Gibraltar, moved east, and taken Carthage from Rome.
They set up a new kingdom in Northern Africa, where they would reside for a century.
**Genseric** was their king, and his son the prince was Huneric.
After going back and forth trying to attack Italy,
they got their true chance when Valentinian killed Aetius,
and in 455, the Vandals managed to enter Rome itself, and plunder it for two weeks.
They sailed away with lots of gold and conquered Sicily.
From this point onwards, their ships were a menace to the Romans.

In 476, a former soldier named **Odoacer** invaded Rome.
He deposed the 16 year old emperor Romulus Augustulus, but didn't kill him.
Odoacer became the first ruler of Italy after Rome, and ended the Western Roman Empire.

==== Byzantine Empire

**Zeno** was the ruler of the Eastern Roman Empire at the fall of the West.
Hoping to be rid of the annoying Theodoric, Zeno appointed him king in Italy,
where he killed Odoacer in Ravenna.
Zeno died by being buried alive while drunk, because nobody opened the sarcophagus.

**Justinian I** (482{n-}565) was an important Byzantine (Eastern Roman) Emperor.
Justinian's wife was Theodora, and his most important general was **Belisarius**.
Belisarius won the **Battle of Tricamarum**,
defeating Gelimer and the Vandals in Northern Africa.

There's a famous mosaic of Justinian and Theodora at Ravenna,
the Ostrogothic capital that Belisarius captured.
His rule was documented in the __Secret History__ of Procopius as well as by Agathias.
Justinian also built the **Hagia Sophia**, the famous domed basilica in Constantinople,
and he notably codified the legislation of the empire in the __Corpus Juris Civilis__,
which was compiled for him by **Tribonian**.

The **Nika Riots** during Justinian's reign
were a result of chariot racing factions uniting against Justinian.
Justinian was forced to fire Tribonian,
and he ordered the instigator, **Hypatius**, nephew of Anastasius,
killed by Belisarius and Mundus.
Belisarius's most notable rival, the eunuch **Narses**,
helped by bribing the Blue racing faction into abandoning Hypatius.

During 541, the **Plague of Justinian** affected the Byzantine Empire,
especially Constantinople.
It was probably caused by __Y. pestis__, which would cause the bubonic plague.
Justinian himself got sick, but he managed to survive.

Other notable rulers of the Byzantine Empire included Basil II and Leo IV, the Khazar.

=== Building a Holy Roman Empire

While Rome's world was collapsing around it,
some new dynasties were being created in what used to be the province of Gaul.
The region was now called Francia, and it was ruled by the Franks, a bunch of Germanic peoples.

==== Merovingian Kingdom

In the fifth century, while Rome was falling,
**Childeric I**, son of Merovech, leader of the Salian Franks,
founded the **Merovingian dynasty**.
It's said that Childeric's father was a half-fish, half-bull monster,
but there's perhaps a slight chance that's just a fabrication.
When Childeric died, he was buried in Saint Brice in Tournai,
with a golden bull's head and lots of golden insects (bees, cicadas, etc.).

Childeric's son was **Clovis I** (481{n-}511), the greatest of the Merovingian rulers.
He was married to Clotilde, and he adopted Christianity, being baptized in 496.
He united Gaul under his rule, and he defeated the remaining Romans
(led by Syagrius, the last Roman official of Gaul),
at the Battle of Soissons.
At the Battle of Vouille (507), he allied with Anastasius I (Byzantine Emperor)
and defeated the Visigoths under Alaric II, conquerer of Spain.
Gregory of Tours would refer to Clovis as a "`new Constantine`" when he wrote his __Histories__.
He would be buried in the Church of the Holy Apostles that he built in Paris.

When Clovis died, his kingdom was divided among his four sons.
To the outside world, these four separate polities were still all the Merovingian kingdom.
Eventually Clotaire II reunited the realm,
and his son **Dagobert I** was the last powerful Merovingian king.
Dagobert expelled the Jews after being asked to by Heraclius, who had prophesied the fall of Byzantium.
After Dagobert, the kings were known as the "`idle kings`" or the "`do-nothing kings`",
so we don't really care enough to discuss them here.

In 687, Pepin the Middle came to power by winning the Battle of Tertry.
Pepin the Middle's son, the prince **Charles "`The Hammer`" Martel** also assumed power.
Martel's sons, Carloman and **Pepin the Short**, appointed Childeric III as the new king.
Pepin the Short was annoyed at not having the title of the King, even though he ruled the Franks.
Childeric didn't do much, Carloman had decided to become a monk or something,
and Pepin's other brother Grifo wasn't a huge opposition.
So Pepin deposed Childeric and colluded with Pope Zachary to get himself elected king.

==== Carolingian Empire

Pepin the Short was the first **Carolingian** king.
He had a good relationship with the papacy, exemplified by his earlier consultation with Zachary.
He helped Pope Stephen II when he helped intervene with the Lombards (a Germanic tribe)
in Italy at battles such as **Pavia**, and Stephen II helped Pepin by crowning him.
He gave the captured lands to the pope, as part of the "`Donation of Pepin`".
In 768, Pepin died, and even though his reign would not be as impressive as his son's,
we can certainly consider him to be a highly successful ruler.

Pepin's son was **Charlemagne**, who co-ruled with his brother Carloman I.
He married Desiderata as a show of alliance with the Lombards.
Carloman died in 771 and Charlemagne became the sole ruler of the Franks.
With his brother's death, he broke his alliance;
he conquered the Lombards led by Desiderius in Italy and became their king.

Charlemagne continued his father's good relationship with the pope,
leading troops into Muslim controlled Spain.
He led campaigns against people who lived east of him,
forcing Christianity on them under penalty of death,
a policy that resulted in the Massacre of Verden.
A leading scholar in his court in Aachen was Alcuin,
who led a "`Carolingian Renaissance`", and established the Palatine school.

On Christmas Day, 800, Charlemagne was crowned Emperor of the Romans by Leo III.
Charlemagne is often referred to as the "`Father of Europe`",
because he united much of the West for the first time since the fall of Rome.
When he died, he was succeeded by Louis the Pious.

Charlemagne and the Franks had recreated a new empire
that strove to be as impressive as Rome itself.
This **Holy Roman Empire**, as it would soon be known,
was set to play a major role in history for centuries to come.

=== Islamic Caliphates

**Muhammad** of Mecca united a large portion of the world under Islam.
Muslims believe that he was a prophet of God and he died in Medina in 632.

==== Rashidun (632{n-}661)

The Rashidun were the "`rightly-guided caliphs`".
**Abu Bakr**, the first caliph to succeed Muhammad, named Umar as his rightful successor,
and after Umar came Uthman.
When Uthman died, a conflict called the first Fitna (Islamic civil war) began.
At this point, **Ali** came to power for a violent five years,
and the followers of Islam split in two.
The followers of Abu Bakr were Sunni Muslims, and followers of Ali were Shi'a Muslims.

The Rashidun spread across all of the Arabian peninsula and much of modern day Iran,
as well as a small portion of Northern Africa.
It was in fact the largest empire ever built up to that point in history.

After Ali's reign, his son Hasan was elected as caliph,
but he gave the caliphate to Mu'awiyah instead.

[[umayyad]]
==== Umayyad (661{n-}750)

**Mu'awiyah** established the Umayyad caliphate,
which expanded across all of northern Africa
and crossed the Strait of Gibraltar to control much of Iberia as well.
It became the fifth-largest empire ever created in history, the largest up to that point,
and its capital was at Damascus.

In 732, the Umayyad fought the **Battle of Tours** against the aforementioned Charles Martel.
The battle took place in northern France, close to the Frankish border,
and the Franks positioned their phalanx on a hilltop.
The Franks won a decisive victory against Abd ar-Rahman,
and the Umayyad were forced to dial down their ambition.
It was at Tours that Charles earned the name "`Martel`", meaning Hammer.
The battle laid the foundation for what would become the <<Carolingian Empire>>.
The Umayyads also lost in 740 to the Byzantines at Akroinon.

Notable caliphs during this time include Yazid I and Mu'awiyah II.
The greatest period of the Umayyad was under Abd al-Malik, while the empire stretched from Spain to India.
The last ruler of the Umayyad was Marwan II.
In 747, a huge rebellion began against the caliphate,
started by people who were annoyed at a distant government.
In 750, Marwan fought an Abbasid army at the **Battle of the Zab**
on the banks of the Great Zab river.
The Abbasids killed Marwan and ended the rule of the Umayyads.

==== Abbasid (750{n-}1517)

The **Abbasid** set up Baghdad as a major city until it was sacked in 1258.
In the 9th century, they created an army that was meant only to fight for them.
These slave soldiers were called **Mamluks**, and eventually they would control Egypt.
The ruler al-Mu'tasim moved the capital from Baghdad to Samarra,
while the Mamluks slowly gained power.

At one point, the dynasty was opposed by Banu and Babak Khorramdin.
During the Anarchy at Samarra, Turkish chiefs fought for control.
They would be sacked by Hulagu Khan at Baghdad, where the House of Wisdom was held.
