== Colonies of the New World

[quote.epigraph, John Winthrop]

  For we must consider that we shall be as a city upon a hill.
  The eyes of all people are upon us.


Remember that Europeans had been colonizing the New World for a while.
Let's actually take a look at what was happening across the Atlantic
and talk about the new colonies and societies that formed there.

=== Pilgrims and Plymouth

Around the turn of the 17th century,
some Puritans in England didn't like the atmosphere of turmoil and persecution that they faced.
These men included the Separatists of Scrooby, and they all decided to go to Holland.
They lived in Leiden for a while, but they didn't really like the Dutch culture,
so they packed up and left.

In 1620, the ship Speedwell left from Delftshaven with the colonists,
met up with its sister ship **Mayflower**, and moved west.
Speedwell was taking on water, and after a failed attempt to fix it, they decided to sell the ship.
Passengers on the Mayflower included Miles Standish, John Alden, and William Bradford.
On the voyage, a passenger named John Howland went overboard, but they got him back.
A baby born on the voyage was named Oceanus and the only passenger to die was William Button.

On the way, the passengers drafted a contract, the **Mayflower Compact**,
which was signed by 41 men on the ship, including John Billington, George Soule, and Edward Winslow.
It organized these **Pilgrims** into a "`civil body politick`".

When they landed at **Plymouth**, Thomas Hunt and others kidnapped some Patuxet.
One of the abductees was **Squanto**, who ended up helping the Pilgrims.

=== Thirteen American Colonies

The colonies would turn into a fairly important country,
so let's look at a couple notable things that happened in each of them.

==== Virginia

The first successful English colony was **Jamestown**,
started by colonists who came over under the command of Christopher Newport.
During the Starving Time, many people died while the colony was directed by George Percy,
and the Starving Time was ended by the arrival of Thomas West, Lord De La Warr.
Lord De La Warr went on to found Henricus, a town nearby.
Jamestown also faced the first strike in the colonies,
in which Polish members of the community refused to work.

Jamestown was dependent on trade with the local Native Americans,
including **Powhatan**.
The tobacco farmer **John Rolfe** married **Pocahontas**,
the daughter of Powhatan, and brought her back to London.
Popular religious leader Alexander Whitaker converted Pocahontas to Christianity.
Captain **John Smith** sent a "`Rude Letter`" to the Virginia Company,
and the company sent the __Sea Venture__, which got shipwrecked.

In 1619, the **House of Burgesses** was established in Jamestown.
The first meeting was presided over by George Yeardley, and the House later moved to Williamsburg.

In 1676, **Bacon's Rebellion**, an uprising of indentured servants and slaves,
occurred under Governor William Berkeley.
The rebellion was started with a disagreement between Giles Brent and some Doeg Indians,
after a Doeg raid on Thomas Matthews's farm.
Skirmishes in the rebellion included massacres of the Occaneechees.
When Bacon died of dysentery, John Ingram became the leader of the rebellion.
The rebellion resulted in the burning of Jamestown.

==== Maryland

**George Calvert, Lord Baltimore** wanted to found a new Catholic refuge in the Chesapeake.
He managed to get a charter for the colony of Avalon, but then he died.

His son, **Cecilius Calvert, Lord Baltimore**, was granted a charter for Maryland,
named after Henrietta Maria, wife of Charles I of England.

==== Delaware

Delaware was home to the Algonquian tribes.
The Dutch were the first to settle there, but they all were killed.
In 1638, **Peter Minuit** established New Sweden for 1651.

In 1651, **Peter Stuyvesant** and his fellow Dutch made a fort at New Castle,
and they annexed New Sweden into New Netherland.

==== New York

In 1624, the Dutch West India Company founded **New Amsterdam** on Manhattan Island.
When Richard Nicholls took it in 1664, he renamed it New York.
With the Treaty of Breda (1667) after George Carteret's capture of Albany,
the capture was confirmed.
Governors of New York include Richard Nicholls, Francis Lovelace, and Sir Edmund Andros.

==== Pennsylvania

In 1681,
Charles II gave a charter to **William Penn** to repay a debt that he owed Penn's father,
along with the land that had previously been known as Upland.
Penn originally called it New Wales, and then Sylvania, but the king renamed it Pennsylvania.
Penn, a Quaker, signed a peace treaty with Tammany of the Delaware tribe,
and there were good relations between Quakers and other tribes.

==== New Jersey

New Jersey was created from New York but the border wasn't finalized for a long time.
The land was given to George Carteret and John Berkeley.

==== Massachusetts Bay

The **Puritans** who wanted to reform the Church of England made the Massachusetts Bay colony.
They wanted to make a nation of saints, a "`City upon a Hill`".

In 1689, there was a revolt in Boston against James II,
and Sir Edmund Andros and others were arrested.

In February 1692, Salem cousins Betty Parris and Abigail Williams started having fits of epilepsy.
They started screaming, throwing things, and enacting scenes from __The Exorcist__,
which was impressive considering it wouldn't be made for another 300 years.
They accused Sarah Good, Sarah Osborne, and **Tituba** of afflicting them with witchery.
Thus began a period of mass hysteria that surrounded the **Salem Witch Trials**.

All sorts of interesting ways of accusing and proving that Salem residents were witches came about.
At one point, Mary Sibley instructed John Indian to make a "`witch cake`".
The cake was made of rye meal and urine from the girls, was fed to a dog,
with the belief that this would hurt the witch.

**Cotton Mather** wrote __Wonders of the Invisible World__ in defense of the trials.
His father, Increase Mather, also wrote about evil spirits and how to deal with them.
The last trial was held in May 1693, and people worked to clear the names of those accused and killed.

==== Rhode Island & Providence Plantations

**Roger Williams**
was banished from Massachusetts Bay because he wanted a better separation of Church and State.
He went and founded Rhode Island, which became a place for refugees,
including **Anne Hutchinson**.
The land was provided by the Narragansett sachem Canonicus.
Williams made a constitution with majority rule, that advocated a "`liberty of conscience`".

==== Connecticut

The main settlers in Connecticut were Puritans led by **Thomas Hooker**.
The Quinnipack Colony was a part of it, and the colony would come to be called New Haven.
Other important settlements include Windsor and Wethersfield.

During the **Pequot War**,
the Pequots besieged Saybrook Colony's garrison and raided Wethersfield.
After they lost at Fairfield, the Pequot asked for peace, having been nearly wiped out.
Other battles during the war include the Mystic Massacre.
The resulting peace was the Treaty of Hartford.

==== New Hampshire

The first permanent settlement in New Hampshire was Hilton's Point, which became Dover.
In 1679, it was the Royal Province,
and **Father Rale's War** was fought between colonists and the Wabanaki Confederacy.

==== Georgia

The British colony was established by **James Oglethorpe** in 1733.
It was intended as an agrarian society with no slaves and lots of farmers.

==== North Carolina

The first incorporated town in North Carolina was Bath,
which is where Edward Teach would have his headquarters.
The first capital of North Carolina would be New Bern.

Early leaders of **Roanoke**, a colony on an island off the coast founded by Sir Walter Raleigh,
included Richard Greenville and Ralph Lane.
John White was another governor, and he left at one point.
The colony worked close with Manteo and Wanchese, who were brought back to England.
When White returned in 1590, he found the word "`Croatoan`" carved into a tree,
and he saw nobody around.

==== South Carolina

South Carolina was a colony, notably situated south of North Carolina.

=== Golden Age of Piracy

In early modern times, there was an explosion of pirate activity on the seas.
Buccaneers in the Caribbean attacked ships all over the colonies.

French pirates had set themselves up on Hispaniola,
but they moved to Tortuga for tactical reasons.
In the mid 1600s, buccaneering flourished,
while Port Royal expanded and allowed them to make even more money.
At the end of the War of the Spanish Succession,
thousands of sailors and privateers didn't have to serve in the military any more,
and the sea trade was booming.

Some important pirates of the era
(either read this section or go play Assassin's Creed IV: Black Flag):

- **Henry Morgan** raided and took Panama, and he was knighted and made governor of Jamaica.

- **William "`Captain`" Kidd** was executed in 1701,
  and he's known now for the treasure he may have buried.

- **"`Black Sam`" Bellamy** was captain of the __Whydah Gally__.
  He was a Robin Hood of pirates who he had his own justifications for piracy.

- **Charles Vane** served under Henry Jennings, then captained his own crew.
  They didn't like him much, and he was marooned, captured, and hanged in 1721.

- **Stede Bonnet** was a landowner in Barbados, and he wanted adventure.
  He captained the __Revenge__, and he was hanged in 1718.

- **Edward Teach, "`Blackbeard`"** is probably the most famous of the pirates.
  He captained the __Queen Anne's Revenge__ and he was killed in 1718 by Robert Maynard.

- **Bartholomew Roberts, "`Black Bart`"** was perhaps the most successful of the pirates.
  He was killed in 1722.

- **Anne Bonny** and **Mary Read** were the most notorious pirate women.
  Read had dressed as a boy for much of her life, and she allied with Bonny.
  They claimed pregnancy to avoid execution when they were caught, but they died anyways.
