== Supreme Court Cases

=== Marbury v. Madison (1803)
__Chief Justice: John Marshall__

John Adams, on his last day in office, named a bunch of new judges under the Organic Act.
The judges are referred to as the "`Midnight Judges`".
The commissions weren't honored by Thomas Jefferson, because he said they were invalid.
**William Marbury**, who would have gotten an appointment as a Justice of the Peace in D.C.,
petitioned Jefferson's Secretary of State, **James Madison**,
to give the commissions using **writs of mandamus**.

Marbury didn't get the commission, and the Judiciary Act was ruled unconstitutional.
Marshall wrote the majority opinion,
and William Cushing and Alfred Moore notably didn't take part in the ruling.
The case is notable because it established **judicial review**,
the process by which the courts can find acts of Congress unconstitutional.

=== McCulloch v. Maryland (1819)
__Chief Justice: John Marshall__

William Pinckney and Daniel Webster won this case,
in which Maryland wanted to impede operation of a branch of the National Bank by taxing bank notes.
The court upheld that this wasn't legal, and granted Congress implied powers to regulate commerce.

=== Gibbons v. Ogden (1824)
__Chief Justice: John Marshall__

A steamboat license was given to Robert Fulton (of __Clermont__ fame).
Some issues of regulation of navigation in state waters ensued.
Aaron Ogden wanted Thomas Gibbons not to be allowed to operate in these waters.
The majority opinion ruled the license unconstitutional,
saying that navigation is in the scope of commerce.

=== Worcester v. Georgia (1832)
__Chief Justice: John Marshall__

The court held that non-Native Americans being on Native American lands
without a license is unconstitutional.
The case laid out the relationship between Native American tribes and the government.
It stated that only the federal government could deal with Native American nations.

=== Dred Scott v. John Sandford (1857)
__Chief Justice: Roger Taney__

Commonly known as the "`Dred Scott case`".
Scott had been taken from the South into free states and territories (Illinois and Wisconsin)
by John Emerson, so he figured he should be free.
In a 7--2 decision, Taney denied this request,
saying that the Missouri Compromise was unconstitutional
(this was the second time a federal statute had been struck down by the court).
Taney said that because Scott wasn't a citizen, he couldn't sue for freedom.

=== __Ex Parte__ Milligan (1866)
__Chief Justice: Salmon P. Chase__

Lambdin Milligan (recall the Knights of the Golden Circle)
was accused of plotting to steal Union weapons and invade Union POW camps.
He and his conspirators were charged, convicted, and sentenced to death by a military tribunal.
In the Supreme Court case, the court determined that trying civilians by military tribunal,
while civilian courts are still functioning, is unconstitutional.
This reversed the previous __Ex parte__ Merryman.

=== Plessy v. Ferguson (1896)
__Chief Justice: Melville Fuller__

Louisiana had passed the Separate Car Act, which required segregation on rail cars.
Homer Plessy bought a ticket on a train and boarded a whites-only car.
He was asked to leave, refused, and was arrested.
His case made it to the court, where the 7--1 vote went against Plessy,
with the dissent being written by John Marshall Harlan,
who claimed that the law was essentially a "`badge of servitude`".
The majority decision, written by Henry Billings Brown,
upheld the constitutionality of "`separate but equal`" facilities,
a doctrine which would remain upheld for another 50 years.

=== Lochner v. New York (1905)
__Chief Justice: Melville Fuller__

Commonly known as just "`Lochner`".
The case involved a law that said a baker could only work ten hours a day, and sixty hours a week.
The court upheld that the law wasn't necessary to protect the health of bakers,
calling it an "`interference with the right and liberty of the individual to contract`".
In his dissent, Oliver Wendell Holmes, Jr. wrote,
"`the Fourteenth Amendment does not enact Herbert Spencer's Social Statics`".
The decision started the __Lochner__ era,
during which the court handed down lots of controversial decisions regarding working conditions.

=== Schenck v. United States (1919)
__Chief Justice: Edward D. White__

Commonly known as **Schenck**.
Schenck was general secretary of the Socialist Party,
and they encouraged distribution of pamphlets that told people to dodge the draft.
So, Schenck and friends were convicted of violating the Espionage Act of 1917.
They appealed all they way to the Supreme Court.

The court ruled unanimously against Schenck,
saying that the First Amendment didn't alter criminal expressions.
Expressions which were intended to result in a crime,
those which presented a "`clear and present danger`" of succeeding, could be punished;
Holmes used the analogy of "`shouting fire in a crowded theater`".
The Schenck decision was overturned by Brandenburg v. Ohio in 1969.

=== Schechter Poultry Corp. v. United States (1935)
__Chief Justice: Charles Evans Hughes__

This case invalidated regulations of the poultry industry,
saying that it was an invalid use of Congress's power.
The unanimous decision rendered the NIRA (recall the New Deal section) unconstitutional.
FDR was understandably annoyed at this decision,
saying that "`we have been relegated to the horse-and-buggy definition of interstate commerce.`"
Justices Hughes and Cardozo agreed that "`extraordinary circumstances`"
don't allow Congress to get more power.

=== Korematsu v. United States (1944)
__Chief Justice: Harlan F. Stone__

Commonly just called **Korematsu**.
Fred Korematsu was an Oakland florist who tried to stay out of WWII-era internment camps.
This led to a case having to do with the constitutionality of Executive Order 9066.
Hugo Black's majority opinion in the 6--3 decision stated that internment was based
on "`pressing public necessity`", not racism, so internment was legal.

=== Brown v. Board of Education (1954)
__Chief Justice: Earl Warren__

Plaintiffs claimed that the system of "`separate but equal`" segregation was unfair,
mostly because the segregated facilities were not equal.
They wanted schools desegregated,
citing Kenneth and Mamie Clark's "`doll test`" studies,
which showed that black children were being badly affected by segregation.
A companion case was introduced in __Briggs v. Elliott__.

The decision was unanimous in ordering the desegregation of schools,
overturning __Plessy v. Ferguson__.
Segregation was deemed a violation of the Fourteenth Amendment,
and schools were ordered to be desegregated with "`all deliberate speed`".

=== Mapp v. Ohio (1961)
__Chief Justice: Earl Warren__

Dollree Mapp was running a numbers game with some other people out of her apartment.
Police got a search warrant and found betting slips and some pornography.
She was arrested and cleared on a misdemeanor charge of possession of numbers paraphernalia.
Later, they decided to prosecute for
``knowingly having had in her possession and under her control certain lewd and lascivious books,
pictures, and photographs in violation of 2905.34 of Ohio's Revised Code''.
She never served any of the sentence, and appealed to the Supreme Court.

The court ruled in a 6--3 decision in favor of Mapp.
They then overturned a previous ruling, __Wolf v. Colorado__.
The Boyd and Weeks decisions were cited and precedent,
and the case affirmed the "`fruit of the poisonous tree`" doctrine.
The exclusionary rule made evidence impermissible in court.

=== Gideon v. Wainwright (1963)
__Chief Justice: Earl Warren__

A burglary took place in a Florida pool hall on June 3, 1961.
A witness claimed he'd seen Clarence Earl Gideon in the poolroom,
and the police arrested Gideon and charged him.
Gideon was denied legal counsel because the Florida court
said only capital cases warranted an appointed lawyer.
He filed suit against the Secretary of the Florida Department of Corrections,
and the case went to the Supreme Court.
Gideon was assigned Abe Fortas (who would become a Supreme Court justice later) to represent him.

In a unanimous decision, the court ruled in favor of Gideon,
saying that Sixth Amendment rights must be given to defendants.
Hugo Black wrote the majority opinion, overturning certain parts of __Betts v. Brady__.

=== Miranda v. Arizona (1966)
__Chief Justice: Earl Warren__

Ernesto Miranda was arrested in Phoenix and linked to the rape of an eighteen-year-old girl.
He signed a confession, but Miranda was never informed of his right to counsel.
The case went to the Supreme Court.
The court, in a 5--4 ruling,
expanded on the rights previously given in __Escobedo v. Illinois__,
and said that officers need to read apprehended suspects their rights.
