== Early United States

[quote.epigraph, George Washington]

  Let us raise a standard to which the wise and honest can repair; the rest is in the hands of God.


=== First Presidents

==== George Washington

The first President of the nascent United States was **George Washington**,
unanimously elected to the position by the electoral college.
His Vice President was **John Adams**,
and his First Lady was **Martha Washington**.

Washington created a Cabinet with four departments: State, War, Treasury, and Justice.
As Secretary of State, he appointed **Thomas Jefferson**.
His Secretary of War was **Henry Knox**,
who had helped him with artillery at Trenton;
Knox would be succeeded by Timothy Pickering.
As Secretary of Treasury, he appointed **Alexander Hamilton**.

**John Jay**, one of the authors of the Federalist Papers,
was sent to negotiate a treaty with Britain.
There had been disputes in the US regarding the evacuation of forts
in the Northwest Territories and the Great Lakes,
so Jay signed a treaty with the British.
**Jay's Treaty**
didn't solve the fact that British ships had been impressing sailors onto their boats,
and some people like Thomas Jefferson thought that it was too friendly to the British.
Popular outrage led to Jay being burned in effigy in the streets.

Another notable treaty was the 1795 **Pinckney's Treaty** (Treaty of San Lorenzo),
which was negotiated with Spain by Thomas Pinckney.
It ended the first phase of the West Florida Controversy,
and it also allowed farmers to ship through New Orleans.

During the **Whiskey Rebellion** (1794),
a bunch of people in western Pennsylvania decided to rise up against excise taxes on liquor.
Alexander Hamilton had proposed the tax, and it wasn't very popular,
but Albert Gallatin (future Treasury Secretary) failed to prevent it.
The governor of Pennsylvania at the time was Thomas Mifflin,
who personally led troops during the conflict.
The rebels were incited by editorials written by "`Tom the Tinker`".
During the rebellion, John Neville's house was burned at the Battle of Bower Hill.
Washington sent **"`Light Horse Harry`" Lee**
and his "`Watermelon Army`" to put down the rebellion.

Washington's Farewell Address is notable because it offered advice to the new country.
Washington talked about the importance of law and of national unity
He warned against making entangling alliances and said that the US should focus on American affairs.
``Whatever may be conceded to the influence of refined education on minds of peculiar structure,
reason and experience both forbid us to expect that national morality
can prevail in exclusion of religious principle.''

==== John Adams

Washington's vice president, John Adams, succeeded him.
Adams's cousin Sam Adams had led the Sons of Liberty,
and his First Lady was **Abigail Adams**.
Adams was the first president to live in the White House.

In the **XYZ Affair**, three French diplomats demanded bribes from Americans.
In response, Charles Cotesworth Pinckney (different Pinckney than the one who signed the treaty)
is thought to have said either
"`No, no, not a sixpence`" or "`Millions for defense, but not one cent for tribute!`"

John Adams also signed the **Alien and Sedition Acts**,
a set of four laws passed in 1798 during the **Quasi-War** with France.
The fourth one was important because it made it criminal to criticize the government and president.
James Madison and Thomas Jefferson opposed the Federalist perspective that these laws created,
as they were clearly designed to weaken the Democratic-Republican party.
To this end, they wrote the **Kentucky Resolution** and **Virginia Resolution**,
which resulted in the Acts being deemed unconstitutional.

==== Thomas Jefferson

===== Office and Policy

**Thomas Jefferson** was John Adams's Vice President.
He was elected president in 1800, in an election against Aaron Burr,
notable because election had to be decided by the House of Representatives,
as Burr and Jefferson were tied in the electoral college.
His second Vice President was **George Clinton**.
Jefferson's Treasury Secretary was originally **Albert Gallatin**, who wanted to reduce taxes.

The First **Barbary War** (1801{n-}1805)
started when Jefferson decided not to pay tribute to the Pasha of Tripoli.
During the war, the USS __Philadelphia__, captained by William Bainbridge,
was captured at Tripoli.
The heroics of **Stephen Decatur** resulted in capturing and burning the ship.
Other important battles of the war include the Battle of Cape Gata and the Battle of Derne.
Tobias Lear, who replaced William Eaton, was a peace envoy in the war.
During the war, the USS __Intrepid__ notably exploded.

Treasury Secretary Gallatin opposed Jefferson's passing of the **Embargo Act** (1807),
which disallowed trade with any foreign countries.
Clearly, this hurt the American economy, and was widely considered a bad move.
Notable political cartoons criticizing the act include one of a turtle biting a man's pants.

===== Lewis and Clark

In 1803, Jefferson doubled the size of the US by executing the **Louisiana Purchase**.
Francois de Barbe-Marbois of France sold the territory
to negotiator Robert Livingston for $15 million
following the Haitian Revolution against Napoleon.
The agreement was nearly stopped
because it almost violated the Treaty of San Ildefonso between Spain and France.
Talleyrand in France and the Federalists in the US opposed the Purchase.

In 1804, Jefferson sent **Meriwether Lewis** and **William Clark**
to lead their expedition into the newly acquired territory.
They left from St. Louis with a group that included
Clark's slave **York**, a child named **Pompy** (Little Pomp),
and a Newfoundland dog named **Seaman**.
On their way, Lewis and Clark constructed Fort Clatsop and Fort Mandan.
Their guides included Old Toby, Touissant Charbonneau, and Charbonneau's Shoshone wife,
**Sacagawea**.
Charbonneau had worked in the North West Company
before starting to trade with the Hidatsas and the Mandan.

===== The Murder and Treason of Aaron Burr

**Aaron Burr** was Jefferson's first Vice President.
He had served in the army during the Revolution, and had become a successful lawyer since.
During his time as President of the Senate, the Senate impeached Supreme Court Justice Samuel Chase.
At the end of his term as Vice President, Burr faced Alexander Hamilton in a duel.
Burr shot and killed Hamilton, but was never tried.

Burr then went west, looking for new opportunities.
He amassed some troops on Blennerhassett Island, and took action.
After trying to help Mexico overthrow its Spanish rule
and take parts of the Louisiana Purchase for himself,
Burr was indicted on charges of treason and imprisoned in Fort Soddet.
The plot was exposed by James Wilkinson,
who had sent a letter to Jefferson
after seeing letters to Anthony Merry and the Marquis of Casa Yrujo.
Burr's defense attorneys included Edmund Randolph, John Wickham, and Luther Martin.
He was acquitted since treason requires two witnesses or an admission of guilt.

=== War of 1812

==== James Madison

Jefferson was succeeded as President by **James Madison**,
who had earlier helped draft the Constitution.
Madison's First Lady was Dolley Madison.
He retained Albert Gallatin as Treasury Secretary.
Madison vetoed the Bonus Bill, which would've used bonuses to create a highway.
Before he took office, the Non-Intercourse Act was signed,
but it was replaced by Macon's Bill No. 2;
both bills had to do with limiting foreign trade,
but weren't as absurdly restrictive as Jefferson's Embargo Act.

==== Course of War

While Madison was President,
a big problem on the seas was the fact that the British Navy was practicing **impressment**;
they would take US sailors and make them work on British ships.
Impressment was a big cause of conflict between the US and Britain,
which became the **War of 1812**.

The **Battle of Lake Erie** (1813), also called the Battle of Put-In Bay,
was a naval battle in which the US took control of the lake.
The American commander was **Oliver Hazard Perry**, who notably said
"`We have met the enemy and they are ours.`"
Perry had earlier served in the Barbary war, notably at the Battle of Derne.
British leaders included Robert Heriot Barclay and Robert Finnis.
Before the battle, Perry took his ships across a sandbar at Presque Isle using "`camels`"
(barges and such that were emptied of any ballast).
Jesse Elliot, an American Lieutenant, controversially wasn't fighting at the start of the battle.
When the Americans took the __Lawrence__,
there was a flag on it saying "`Don't give up the ship`".

At the **Battle of Bladensburg** (1814),
the British under Robert Ross decisively defeated the US under William Winder.
The British had amassed their ships on Tangier Island and launched rockets against the Americans.
As a result of the battle,
the British walked into Washington and burned the White House and other important things.
Bladensburg and the burning of D.C. have been called
the "`greatest disgrace ever dealt to American arms`".

**Francis Scott Key** penned **The Star Spangled Banner**
during a battle at **Fort McHenry**.
Other battles in the war include Chateauguay, Crysler's Farm, and Prophetstown,
while the bloodiest battle was Lundy's Lane.
Laura Secord, a Canadian heroine,
walked 20 miles out of US-occupied territory in 1813 to warn the British of an attack;
she's now mostly remembered because of the Canada-made Laura Secord Chocolates,
which she didn't really have anything to do with.

The **Treaty of Ghent** ended the war.
Important American negotiators were Henry Clay and John Quincy Adams.
During the negotiation, the British launched multiple invasions,
stopping after Plattsburg and Bladensburg.
The treaty notably asks the Americans to stop fighting with the Native Americans
and create a new barrier state in the Northwest Territory.

Two weeks after the treaty was signed, the **Battle of New Orleans** took place,
because they hadn't gotten the memo yet.
The Americans were commanded by **Andrew Jackson**
against British forces under **Edward Pakenham**.
Jackson had earlier won the Battle of Pensacola against Creek and British forces.
The American army was notably assisted by the French pirate **Jean Lafitte**.
Other American commanders included John Coffee and William Carroll,
while British officers included Admiral Alexander Cochrane and Thomas Mullins.
Much of the fighting occurred at Rodriguez Canal,
where the British tried to fill the canal with sugarcane (they failed).
At one point,
British troops under Thomas Mullins forgot the ladders needed to scale American earthworks,
leading to confusion and necessitating Pakenham's reinforcement with the missing ladders.
Choctaw fighters tried to surround the Americans by attacking through marshes.
There was also fighting at Fort Bowyer and Fort St. Philip.
The battle ended with only 71 American casualties and over 2,000 British casualties.

=== Nationalism and Reform

==== Era of Good Feelings

**James Monroe** was elected to the presidency in 1816.
He was the last President to have been a Founding Father,
and he'd fought in the Revolutionary War and had been wounded at Trenton.
While governor of Virginia, he had faced **Gabriel Prosser's Rebellion**.
At this point, the Federalists were a broken and failing party,
so Monroe defeated Rufus King and took the presidency easily.

The time he was president is called the "`Era of Good Feelings`"
because there was effectively one party.
His Secretary of State was **John Quincy Adams**, John Adams's son.
Monroe issued the **Monroe Doctrine**,
which prohibited European countries from interfering with the Western hemisphere.
The **Adams-Onis Treaty** (1819) was signed, buying Florida from Spain.
Spain had claimed West Florida as a consequence of the 1783 Treaty of Paris.

In 1820, **Henry Clay** passed the **Missouri Compromise**.
It temporarily reconciled the pro-slavery and anti-slavery factions in Congress.
The compromise prohibited slavery north of 36{deg}30' N, except in Missouri.
Because Missouri was admitted as a slave state,
Maine was split from Massachusetts and admitted as a free state.
A follow-up passed to the compromise added an exclusionary clause for mulattoes.
James Tallmadge tried to pass the Tallmadge Amendment,
which would have freed some slaves when they turned 25.

==== Seminole Wars

The **First Seminole War** was fought from 1816 to 1819, while Monroe was in office.
General Andrew Jackson had been going into Spanish Florida
to fight before the US took control of the area.
Britain and Spain weren't very happy with this arrangement,
but eventually the Adams-Onis treaty gave Florida to the US.
The Treaty of Moultrie Creek, or Fort Moultrie, forced the Seminoles to leave north Florida.

The **Second Seminole War** (1835{n-}1842)
started when the US tried to make the Seminoles leave Florida completely,
as a result of the **Treaty of Payne's Landing** (1832).
**Osceola** was an important Seminole leader at the start of the war.
Seminoles claimed they signed the treaty under duress,
and they used guerrilla warfare against American troops.
Many Seminoles died, and the ones that weren't were forced to Oklahoma.
During the Dade Massacre, the Seminoles decisively defeated US forces under Major Francis Dade.

The **Third Seminole War** (1855{n-}1858) was provoked when settlers went into Seminole territory.
Chief Billy Bowlegs raided Fort Myers in 1855.
The rest of the Seminoles were forced to go to Oklahoma,
and only about 100 of them remained in the Everglades.

==== John Q. Adams

The election in 1824 was a strange one.
None of the candidates had a majority in the electoral college,
so it fell to the House to select the president.
Surprisingly, the House picked **John Quincy Adams** over Andrew Jackson.
Many people believed that Adams had struck a **corrupt bargain** with **Henry Clay**.
It was claimed that in exchange for Clay convincing the House to pick Adams,
Adams would make Clay his Secretary of State.

While president, Adams was opposed at every turn by Jacksonians who resented him.
He appointed Robert Trimble to the supreme court.
By the end of the presidency, he had endured a terrible argument with the British West Indies,
and he had built the Dismal Swamp Canal and some other useful transportation routes.

==== Andrew Jackson

**Andrew Jackson**, "`Old Hickory`", known as "`Sharp Knife`" to Native Americans,
took the presidency in the 1828 election.

During the beginning of his administration, Jackson dealt with the **Peggy Eaton Affair**,
in which a bunch of his cabinet members
and their wives were targets of vicious attacks concerning their morality.
Jackson eventually concluded that John C. Calhoun was responsible for the rumors,
but Secretary of War John Eaton and his wife Peggy ended up shunned by many.
Jackson also had an unofficial **Kitchen Cabinet** which contained a bunch of his advisors.

If you've seen __The West Wing__,
you'll know that Jackson once put a two-ton block of cheese
in the White House and invited anyone to eat from it.
This was intended to show openness to the American people.
In 1830, he struck down the **Maysville Road bill**,
vetoing a bill that would allow the government to buy stock in a road company
to construct a road in Kentucky.

While president, Jackson initiated a whole new set of Indian removal policies.
In 1830, Congress passed the **Indian Removal Act**,
which resulted in the Cherokee having to be relocated.
Leaders of the Cherokee included John Ridge,
who negotiated the **Treaty of New Echota** with Jackson.

During the **Nullification Crisis** (1828{n-}1832), Jackson faced controversy over tariffs.
The 1828 **Tariff of Abominations**
was protested by South Carolinian Vice President **John C. Calhoun**.
Calhoun claimed that the state should be able to nullify the tariff,
and he wrote the __South Carolina Exposition and Protest__.
Jackson supported a strong union, opposing Calhoun.
The Verplanck Bill almost ended the crisis,
but eventually the Force Bill was passed,
expanding the power of the presidency and compelling compliance.

The **Second Bank of the United States** had been created in 1816 by Madison.
In 1823, **Nicholas Biddle** was appointed as executive of the Bank.
Biddle submitted a recharter for the Bank in 1832,
but Jackson really didn't like the Bank, so he vetoed the bill.
Jackson also issued the **Specie Circular**,
an executive order that compelled government land to be paid for using gold or silver.

The election of 1832 featured the Bank as a central issue.
Jackson and Martin van Buren were nominated from the Democratic Party.
The National Republican Party nominated Henry Clay and John Sergeant,
while the Anti-Masonic party nominated **William Wirt** and Amos Elmaker,
because Jackson and Clay were both masons.
Jackson was quite popular at this point, achieving a solid victory and reelection.

In 1835, Richard Lawrence, the first known failed presidential assassin,
tried to shoot Jackson outside the Capitol.
When Jackson died in 1845, he was buried at his house, **The Hermitage**, in Nashville.

==== Martin Van Buren

**Martin Van Buren** had been Jackson's Vice President,
and Jackson had previously appointed him as Minister to Great Britain until Calhoun shut that down.
He'd been Secretary of State until the Peggy Eaton affair.
He had developed the Albany Regency, a political machine.

Van Buren was elected to the presidency in 1836, and he served one term.
His Vice President was Richard Mentor Johnson,
and his Secretary of State was **Daniel Webster**.

During the **Panic of 1837**, the economy collapsed.
This was followed by five years of depression, sometimes attributed to Jackson and his Bank War.
Van Buren denied Texas's request to join the Union, trying to keep the world together.

During the 1838 Mormon War, **Joseph Smith** and the Mormons were forced from Missouri.
Smith tried to get Van Buren to help the Mormons, but Van Buren refused.

Following the Treaty of New Echota,
the Cherokee and other Florida tribes went on the **Trail of Tears**.
Winfield Scott had set up internment camps to prepare for Indian removal.

In 1839, a small incident arose regarding the border between Maine and New Bruns-wick, Can-ada.
The bloodless **Aroostook War**
occurred when loggers from both countries disputed where they could cut trees.
William I of the Netherlands tried to help mediate the conflict
after John Baker tried to create the Republic of Madawaska, but he failed.
Forts constructed as causes of the war included Fort Kent, Fort Fairfield, and Fort Blunder.
The Webster-Ashburton Treaty,
negotiated by Daniel Webster, Winfield Scott, and Alexander Baring,
ended the dispute.

==== Tippecanoe and Tyler Too

===== William H. Harrison

**William Henry Harrison** had been an important Army general
in an earlier war with **Tecumseh**.
Around 1810,
Tecumseh and his brother **Tenskwatawa** (The Prophet) led fighters and met Harrison.
At the **Battle of Tippecanoe** (1811), near Prophetstown, Harrison defeated tribal forces.
Harrison was hailed as a hero.
During the War of 1812, Harrison had fought at the Battle of the Thames, where Tecumseh died.
He'd been the Northern Whig candidate for the presidency in 1836.

In 1840, he ran against Van Buren, calling him "`Van Ruin`".
The campaign slogan was "`Tippecanoe and Tyler Too`", referencing Harrison's most notable victory.
Harrison won a landslide electoral victory.

At his inauguration, Harrison wanted to show that he was still a great military hero.
So, even though it was cold and wet outside, he didn't wear a coat or hat,
and proceeded to give the longest inaugural address ever given.
Thirty days later, he contracted pneumonia and died.
He was the first president to die in office, having served the shortest term of any of them.

===== John Tyler

**John Tyler**, "`His Accidency`", took the presidency on Harrison's death.
Tyler sent Caleb Cushing to negotiate the Treaty of Wanghia with China.
He lost Secretary of State Abel Upshur and Secretary of the Navy Thomas Gilmer
when the USS __Princeton__ exploded.
He also annexed Texas.

When Tyler broke with the Whig party over bank issues, almost everyone in his cabinet resigned,
Daniel Webster stayed around to finalize the Webster-Ashburton Treaty.

In 1842, Tyler faced the **Dorr Rebellion** in Rhode Island,
but he decided not to send troops to stop it.
When state militia marched on the rebels, the rebels ran away.
