== Dawn of Civilization

[quote.epigraph, Hammurabi]
To bring about the rule of righteousness in the land so that the strong shall not harm the weak.

=== Mesopotamia

First, it's worth noting that **Sumer** existed around 3000 BC.
Having been founded with the settlement of Eridu,
the civilization's major city would come to be known as **Ur**,
Later, Ur became very important in the changes that civilization would go through.
Sumer also had a period of history called Uruk during which **cuneiform**,
a wedge shaped writing system, was developed.
The kings of the city-states of Sumer were called lugals,
and the people used irrigation canals to farm all year.

One of the first notable rulers in Mesopotamia was **Sargon I** of Akkad,
who conquered much of Sumer.
He fought a war against Ur-Zababa
prior to becoming one of the greatest conquerors the world had ever seen.
His capital was never found.
The dissolution of his Akkadian Empire led to the establishment of two important powers:
Babylonia and Assyria.

**Hammurabi of Babylon** ruled around 1800 BC.
Notably, he made a code of law can be summarized with "`an eye for an eye`"
--- it was quite harsh and painful.
The code was carved on a column in Susa
and it discusses the consequences for slaves that disobey their masters.
The epilogue of the code thanks the gods Zamana and Ishtar, important gods around the time.
Now, having been rediscovered, the code sits in the Louvre.

The last king of the Neo-Assyrian empire was **Ashurbanipal**,
son of Esarhaddon son of Sennacherib.
His library, a huge collection of cuneiform documents he kept in Nineveh,
is in the British Museum now.
He reportedly salted the earth after defeating the Elamites and taking their capital at Susa.
The death of Ashurbanipal led to the downfall of the Neo-Assyrian empire.

A Chaldean king, **Nebuchadnezzar II**,
was well known for building the **Hanging Gardens of Babylon**.
He defeated Necho II of Egypt at the **Battle of Carchemish** in 605 BC,
and reconquered Jerusalem, destroying the city and the temple within.
In addition to the Hanging Gardens,
Nebuchadnezzar also put together the Ishtar Gate, Entemananki, Ezika, and Esagila.

=== Ancient Egypt

In Egypt, pharaohs were building pyramids and other big things.
Here are some notables:

**Djoser** was a king of the 3rd dynasty (Old Kingdom),
and he was buried in a notable namesake pyramid.
He worked with his vizier **Imhotep** (the guy from __The Mummy__)
to make it, and Imhotep was one of the most important people during that time.

**Akhenaten** (1353--1336 BC), formerly Amenhotep IV,
completely reorganized all the religion in Egypt.
He worshiped Aten (a solar disc) instead of the old religion.
This didn't exactly ingratiate him with the priests of the time,
and he fell out with them 5 years into ruling.
He was married to **Nefertiti**, a daughter of Ay who didn't come from royal blood
and his son was **Tutenkhamen** (who was a very young king).
He constructed Amarna and was succeeded by Smenkhare.

**Rameses II, The Great** (1279--1213 BC) fought the Hittites at the **Battle of Kadesh**,
near the Orontes River, where over 6,000 chariots were used;
the battle was fought to a draw.
Rameses also suppressed the Shardana pirates in a naval battle.
His father was Seti I, who did some military things.
Rameses built the **Abu Simbel** temples and a temple at Luxor that houses the House of Life.
His wife was **Nefertari**, daughter of Hattusilis, and the Greeks called him Ozymandias.
He built the Karnak complex
and he was succeeded by Merneptah I when he was buried in the Valley of the Kings.

=== Indus River Valley

Further East, some small civilizations were cropping up in the **Indus River Valley**.

Notably, these include **Harappa** and **Mohenjo-Daro**,
which date to the 27th century BC.
Mohenjo-Daro had a famous Great Bath and a College of Priests.
These were the centers of the civilization.
Even though I don't really have much else to say on the subject, they really are quite notable.
