== Dawn of Civilization

[quote.epigraph, Hammurabi]
To bring about the rule of righteousness in the land so that the strong shall not harm the weak.

=== Mesopotamia

First, it's worth noting that **Sumer** existed around 3000 BC.
Having been founded with the settlement of Eridu,
the civilization's major city would come to be known as **Ur**,
Later, Ur became very important in the changes that civilization would go through.
Sumer also had a period of history called Uruk during which **cuneiform**,
a wedge shaped writing system, was developed.
The kings of the city-states of Sumer were called lugals,
and the people used irrigation canals to farm all year.

One of the first notable rulers in Mesopotamia was **Sargon I** of Akkad,
who conquered much of Sumer.
He fought a war against Ur-Zababa
prior to becoming one of the greatest conquerors the world had ever seen.
His capital was never found.
The dissolution of his Akkadian Empire led to the establishment of two important powers:
Babylonia and Assyria.

**Hammurabi of Babylon** ruled around 1800 BC.
Notably, he made a code of law can be summarized with "`an eye for an eye`"
-- it was quite harsh and painful.
The code was carved on a column in Susa
and it discusses the consequences for slaves that disobey their masters.
The epilogue of the code thanks the gods Zamana and Ishtar, important gods around the time.
Now, having been rediscovered, the code sits in the Louvre.

The last king of the Neo-Assyrian empire was **Ashurbanipal**,
son of Esarhaddon son of Sennacherib.
His library, a huge collection of cuneiform documents he kept in Nineveh,
is in the British Museum now.
He reportedly salted the earth after defeating the Elamites and taking their capital at Susa.
The death of Ashurbanipal led to the downfall of the Neo-Assyrian empire.

A Chaldean king, **Nebuchadnezzar II**,
was well known for building the **Hanging Gardens of Babylon**.
He defeated Necho II of Egypt at the **Battle of Carchemish** in 605 BC,
and reconquered Jerusalem, destroying the city and the temple within.
In addition to the Hanging Gardens,
Nebuchadnezzar also put together the Ishtar Gate, Entemananki, Ezika, and Esagila.

=== Ancient Egypt

From c. 7000 BC to 3000 BC, the Nile Valley was being settled and generally
consisted of disjointed groups which eventually coalesced into
**Upper Egypt** and **Lower Egypt**.
Upper Egypt was to the south ("`up`" the Nile), while Lower Egypt was to the north.

[sidebar]
Some of the early Egyptian history here is fairly sketchy;
there tends to be some debate amongst historians regarding certain dates and identities.
A nontrivial amount of information regarding the chronology of rules
eventually ends up tracing back to the **Turin King List** (aka the Turin Royal Canon),
a papyrus ostensibly created during the reign of Rameses II and now housed in Turin.
The information contained therein is dubious for early Egyptian history,
and half of it is missing anyway.

==== Early Dynastic Period

Circa 3100 BC, the two kingdoms began to intertwine in both culture and economics.
Thus began the **First Dynasty** of Egypt.
The first pharoah post-unification was likely **Narmer**,
a king often identified as **Menes** in the Greek classical tradition
(there's still some debate around this).

An important archaeological find from this period is the **Narmer Palette**,
which depicts the White Crown of Upper Egypt along with the Red Crown of Lower Egypt.

==== Old Kingdom (c. 2686{n-}2181 BC)

**Djoser** of the Third Dynasty was the first King of the Old Kingdom,
and he was buried in a notable namesake step pyramid at Saqqara, near Memphis.
He worked with his vizier **Imhotep** (the guy from __The Mummy__)
to make it, and Imhotep was one of the most important people during that time.

During the Third Dynasty, independent Egyptian states became called **nomes**,
with each ruled by a nomarch.
Each nome was under the ultimate rule of the king.

That brings us to the Fourth Dynasty,
which began with Snefru (known sometimes as Soris),
who became a prolific pyramid commissioner.
Snefru ordered the building of three pyramids:
the Meidum pyramid, the Bent Pyramid at Dahshur, and the Red Pyramid.

Snefru was succeeded by **Khufu** (known to the Greeks as Cheops),
who most famously built the Great Pyramid at Giza.
Not much else is documented about his reign,
but he is the main character in the Westcar Papyrus
(a collection of some stories about miracles).

Later kings of the Fourth Dynasty included **Menkaure**,
who also built a pyramid in Giza.

The Fourth Dynasty gave way to the Fifth,
which ended in the First Intermediate Period.
At this point, pharaonic power was greatly diminshed and power became decentralized.

==== Middle Kingdom (c. 2050{n-}1710 BC)

That all ended when the Eleventh Dynasty reunited under Mentuhotep II.
The Middle Kingdom gave rise to old styles of government,
resulting in the readoption of the vizier as a position of great power.

However, by the end of the Thirteenth Dynasty,
dynastic chaos began to once again take hold of the Kingdom.
Thus begins the full disintegration of unity once again,
resulting in the Second Intermediate Period.

==== New Kingdom (c. 1550{n-}1069 BC)

The Eighteenth Dynasty was home to perhaps the most famous figures of Egypt.

**Ahmose I** is the accepted founder of the Eighteenth Dynasty.
He campaigned against the Hyksos and the Levant.
He was followed by Amenhotep I and Thutmose I.

Thutmose I was succeeded by Thutmose II, who married Thutmose I's daughter, **Hatshepsut**.
She came to power after Thutmose II's death, ruling jointly with Thutmose III.
Widely considered a hugely successful pharaoh,
Hatshepsut built much of the Karnak temple in Luxor
including a __Chapelle Rouge__ (Red Chapel) from which we learned about her.
She created an era of prosperity due to redeveloping trade networks
and funded a mission to Queen Ati of the Land of Punt,
which notably brought back myrrh and frankincense.
The expedition was commemorated with a temple at Deir el-Bahri.
Hatshepsut was succeeded by Thutmose III upon her death.

[sidebar]
It is at this point that the word "`pharaoh`" actually came to refer to the person in power,
rather than just the palace in which the King of Egypt resided.

**Thutmose III**,
having learned of military strategy during his time as co-regent with Hatshepsut,
grew into an immensively successful expansionist.
Sometimes referred to as "`the Napoleon of Egypt`",
he captured hundreds of eastern cities and crossed the Euphrates.

**Amenhotep III** built the Luxor Temple and multiple other huge palaces.
He was the richest of the Eighteenth Dynasty kings.

**Akhenaten** (1353{n-}1336 BC), formerly Amenhotep IV,
completely reorganized all the religion in Egypt.
He worshiped Aten (a solar disc) instead of the old religion.
This didn't exactly ingratiate him with the priests of the time,
and he fell out with them 5 years into ruling.
He was married to **Nefertiti**, a daughter of Ay who didn't come from royal blood
and his son was **Tutenkhamen** (who was a very young king).
He constructed Amarna and was succeeded by Smenkhare.

**Rameses II, The Great** (1279{n-}1213 BC) fought the Hittites at the **Battle of Kadesh**,
near the Orontes River, where over 6,000 chariots were used;
the battle was fought to a draw.
Rameses also suppressed the Shardana pirates in a naval battle.
His father was Seti I, who did some military things.
Rameses built the **Abu Simbel** temples and a temple at Luxor that houses the House of Life.
His wife was **Nefertari**, daughter of Hattusilis, and the Greeks called him Ozymandias.
He built the Karnak complex
and he was succeeded by Merneptah I when he was buried in the Valley of the Kings.

=== Indus River Valley

Further East, some small civilizations were cropping up in the **Indus River Valley**.

Notably, these include **Harappa** and **Mohenjo-Daro**,
which date to the 27th century BC.
Mohenjo-Daro had a famous Great Bath and a College of Priests.
These were the centers of the civilization.
Even though I don't really have much else to say on the subject, they really are quite notable.
