== Expansion and Civil War

[quote.epigraph, William Tecumseh Sherman]

  War is hell.


We look at the entire middle of the 19th century in America in this chapter,
starting with the Mexican-American War and going straight through to the end of Reconstruction.

=== War With Mexico

==== James K. Polk

The election of 1844 resulted in Democrat **James K. Polk**, "`Young Hickory`",
defeating the Whig Henry Clay,
following Clay's third and final attempt to take the office.
Polk, who was governor of Tennessee,
had been a dark horse who got the nomination over Lewis Cass and Martin Van Buren.

Polk's Vice President was **George M. Dallas**.
Robert Walker, Secretary of the Treasury, passed the **Walker Tariff**,
which helped a border dispute in Oregon;
this resulted in Polk acquiring some of the Oregon territory for the US.
Secretary of the Navy George Bancroft established Annapolis Naval Academy,
and Polk established the Smithsonian.
As president, he also created the Department of the Interior.

==== Revolution in Texas

In 1836, American settlers in Texas (a part of Mexico)
decided they didn't want to be Mexican any more.
So they declared independence and created the **Republic of Texas**.
While Mirabeau B. Lamar was President of Texas, Texas printed "`red back`" currency.

Mexican President **Antonio Lopez de Santa Anna** decided to take Texas back.
His general Jose de Urrea led the Goliad campaign up the coast,
killing almost all troops he encountered.

Santa Anna himself led a force that marched to San Antonio,
where he met a Texan garrison at the **Alamo**.
Before the Battle of the Alamo, the commander William Travis acknowledged certain death.
He drew a line in the sand
and said that anyone who wanted to could cross the line and fight with him.
Everyone crossed the line except for Moses Rose, who ran away.
Defenders at the Alamo included **Davy Crockett** and Jim Bowie.
Travis responded to Santa Anna's request for surrender by firing cannons at him.
The garrison of about 200 men died fighting Santa Anna, in a battle that is remembered to this day.

The Texans, under **Sam Houston** (first president of Republic of Texas),
came back to ambush Santa Anna's forces at **San Jacinto**.
The battle didn't even last 20 minutes because the Texans caught the Mexicans on a siesta.
The Texans also had some impressive cannons called the "`Twin Sisters`".
Battle cries included "`Remember Goliad`" and "`Remember the Alamo!`".
The battle was a decisive victory for the Texans,
and it resulted in the capture of Santa Anna and the signing of Treaties of Velasco.

Texas was annexed into the Union in 1845, ending the Lone Star Republic.
Just before the deal was set, the Regulator-Moderator war was quelled.
The plan was proposed by Anson Jones,
and Texas reserved the right to split into five states in the future.
In 1850, a payment of $10 million helped Texas repay its debts.
Later in Polk's presidency,
the question of the southern border of the Nueces River for the state
would be brought into question.

==== Course of War

Precipitated by the Thornton Affair, a battle along the Rio Grande,
the **Mexican-American War** lasted from 1846 to 1848.
The US quickly took New Mexico and California.

The war featured some notable fighting groups.
St. Patrick's Battalion was a group of Irish Catholic soldier
who defected and were subsequently hanged.
The Mormon Battalion, the only religious military unit in US history,
was led by Philip Saint George Cooke.

At the Battle of Chapultapec, US Marines stormed a castle on a hill,
the site of a Mexican military academy.
They won, and in the process, they killed the six "`Boy Heroes`" (Los Ninos Heroes),
Mexican military cadets who wouldn't fall back when ordered by General Bravo.

**Zachary Taylor** led land forces to win at battles at Monterrey and Buena Vista.
Winfield Scott and Matthew Perry ran the first successful
American amphibious landing at **Veracruz**.
They besieged the city and took it.

In 1846, Californian settlers under William B. Ide captured Sonoma and General Mariano Vallejo.
This initiated the **Bear Flag Revolt**,
and John Fremont (the Pathfinder) and Robert Stockton became leaders.
The revolt was put down by Stephen Kearny during his conquest of California during the war.

The war was ended by the **Treaty of Guadalupe-Hidalgo**.
Nicholas Trist and John Slidell were negotiators at the treaty,
but Trist's disobedience of Polk's instructions made Polk mad at him.
Trist had been ordered to offer $30 million to get Baja California and more territory in the South.
When Trist finished with the treaty, he had taken less land, and he got money from Mexico,
and was promptly fired on returning to Washington.

=== American Frontier

==== Outlaws of the Wild West

Certainly you know about the numerous outlaws and renegades that wandered the Old West,
killing and robbing town all over the frontier.
In this section, we look at some of the most famous of these people and the ones who chased them.

**Jesse James**::
  James (1847-1882) was an outlaw from Missouri who associated with the James-Younger Gang.
  During the Civil War,
  James and his brother were Bushwhackers (guerrillas)
  who may have participated in the Centralia Massacre.
  In 1882, James was shot by **Robert Ford**, a member of his own gang, for reward money.

**Wild Bill Hickok**::
  Now a legend, he had become a fugitive as a teenager.
  He fought for the Union during the Civil War, and he was involved in lots of shootouts.
  He was killed by Jack McCall in Deadwood (in the Black Hills),
  while holding a poker hand including black aces and eights.
  The hand would come to be called the "`Dead Man's Hand`".

**Wyatt Earp**::
  A sheriff who served in Tombstone, Arizona.
  He's most well known for participating in the **Gunfight at the O.K. Corral**,
  a 30-second gunfight at which Tom and Frank McLaury and Billy Clanton were killed.

**Doc Holliday**::
  Also at O.K. Corral, as a temporary deputy.
  Holliday had become a dentist when he was young, but then he got tuberculosis and moved west,
  where he became friends with Earp.
  Following the shootout, Earp took Holliday as part of his Vendetta Ride posse,
  and the local sheriff issued a arrest warrants for the posse.
  Holliday eventually died in Colorado from the tuberculosis.

**Billy the Kid**::
  Perhaps the most infamous of the Wild West gunmen.
  His real name was William H. Bonney, and it's said that he killed 21 men,
  even though it was probably more like 8.
  In 1881, a bounty was placed on his head by the governor of New Mexico, Lew Wallace.
  He was shot and killed when he was 21.

==== California Gold Rush

In 1849, James Marshall struck gold at **Sutter's Mill**.
John Sutter was a Swiss pioneer who had tried to make New Helvetia,
a colony near modern day Sacramento.
However, the gold discovery and resulting **California Gold Rush**
didn't really help his plans.
The so-called 49ers, gold hunters, showed up in California in droves,
looking to make their fortunes.
Word spread when people like Samuel Brannan, publisher of the __Star__,
publicized discovery of gold.

During the gold rush,
brand new techniques like coyoteing, dredging, and improvements on gold panning were pioneered.
**Levi Strauss** sold denim overalls to help out the 49ers.
To get to California, the 49ers used the Siskiyou Trail to get to places like Coloma, CA.

=== Antebellum America

==== Zachary Taylor

In the 1848 election,
Lewis Cass and Martin Van Buren were defeated by Whig **Zachary Taylor**,
"`Old Rough-and-Ready`".
Taylor had fought in the Mexican-American War,
winning at both Palo Alto and Buena Vista even though he was outnumbered three to one.
Before that, he had won the Battle of Lake Okeechobee during the Seminole Wars.
Taylor's Secretary of State was John M. Clayton.
Clayton negotiated the **Clayton-Bulwer Treaty**,
which said that canals in Central America
should be controlled by both the US and Britain and open to all countries.

==== Millard Fillmore

In the middle of 1850, Taylor got cholera after eating fruit and milk, and died.
He was succeeded by **Millard Fillmore**, his Vice President,
whom history has proved to be one of the worst presidents ever.
Fillmore ran again in 1856 as a member of the Know-Nothing Party.
During his presidency,
Commodore Matthew Perry signed the Treaty of Kanagawa with the Tokugawa Shogunate.

In 1850, Henry Clay helped write the **Compromise of 1850**.
The Compromise admitted California to the union as a free state,
banned slave trading in Washington, DC,
contained a strong **Fugitive Slave Act**,
and gave popular sovereignty to Utah and New Mexico.
During debate over the Compromise, William Seward gave his "`Higher Law`" speech opposing it,
saying that "`there is a higher law than the Constitution`".
Other opponents included John Calhoun,
but Webster and Douglas reworked Clay's original compromise and got it passed.

==== Franklin Pierce

The candidates in the election of 1852 were
**Franklin Pierce** the Democrat,
Winfield Scott the Whig,
and John P. Hale of the Free Soil Party.
Pierce won the election in an electoral landslide.
His Secretary of State was William Marcy,
and his Secretary of War was Jefferson Davis, who would become President of the Confederacy.

In 1854, Marcy met with some American ministers in Europe to discuss acquiring Cuba for the US.
They met in Aix-la-Chapelle and drafted the **Ostend Manifesto**.
It was quickly hated in the north of the USA and in Europe.

Also in 1854, the **Kansas-Nebraska Act** was passed,
repealing the Missouri Compromise of 1820.
The Act had been written by Senator **Stephen Douglas** from Illinois,
and it created the territories of Kansas and Nebraska,
allowing settlers in each territory popular sovereignty to decide if they wanted to allow slavery.

Pierce also signed the **Gadsden Purchase** on April 25, 1854.
The purchase included southwestern New Mexico and southern Arizona (south of the Gila River),
and it was signed by James Gadsden,
former president of the South Carolina Railroad Co. and current US ambassador to Mexico.
It was made because the US was thinking about making a transcontinental railroad.
However, it was so unpopular in Mexico that Santa Anna was ousted as dictator.

==== James Buchanan

**James Buchanan** was elected president in 1856,
defeating Republican John C. Fremont and "`Know Nothing`" Millard Fillmore.
He was notably the only bachelor president, and his Vice President was John Breckinridge.
Lewis Cass, his Secretary of State, quit while Buchanan was in office.
Buchanan had been Secretary of State for Polk,
and he'd helped write the Ostend Manifesto as minister to Britain.

In 1856, the **Lecompton Constitution** was drafted for Kansas.
It was pro-slavery, and Buchanan endorsed it (not a good call).
Stephen Douglas was against the constitution,
and governor Robert J. Walker resigned over controversy regarding it.
As a result, Free-Staters and Border-Ruffians got into a conflict in the territory,
during a period we now call **Bleeding Kansas**.

**Charles Sumner** was a senator from Massachusetts,
and during the Bleeding Kansas crisis, he denounced the Kansas-Nebraska Act in the Senate.
His "`Crime against Kansas`" speech attacked Andrew Butler and Stephen Douglas,
calling them Don Quixote and Sancho Panza, respectively.
Butler's nephew, **Preston Brooks**, didn't like the speech;
he took a cane and beat Sumner in the Senate chamber.
During the caning of Sumner, Laurence Keitt reportedly waved a gun around and said "`let them be!`"

==== Abolitionism

At this time, abolitionism was also picking up steam,
partly under the violent leadership of **John Brown**.
Brown had led the Pottawatomie Massacre near Lawrence, Kansas
during Bleeding Kansas, killing five settlers.

In 1859, Brown took 21 men, funded by rich people called the Secret Six,
and led a raid on the United States Arsenal at **Harper's Ferry** in Virginia.
The first person to die in the raid was Dangerfield Newby,
and the raid was stopped by General Robert E. Lee and J.E.B. Stuart.
Brown was captured and hanged;
notably, Stonewall Jackson guarded him while awaiting execution.

The **Free Soil Party** was a party that advocated abolition.
In 1948, the **Barnburner** faction (opposed to the Conscience Whigs),
nominated their leader Martin Van Buren for the presidency.
Salmon P. Chase coined the Free Soilers' slogan, "`Free Soil, Free Labor, Free Men`".

In opposition to the abolition movement were the **Knights of the Golden Circle**.
They were led by Clement Vallandigham, and they would try to help the Confederacy defeat the Union
and spread slavery.

=== Civil War

Of course, all of this conflict brewing in the country in the 1850s would turn into a pivotal war.
Let's examine the causes and course of the American Civil War.

==== Background Miscellany

**John J. Crittenden** had been the Attorney General
for Millard Fillmore and William H. Harrison.
In 1860, as senator from Kentucky, Crittenden proposed the **Crittenden Compromise**
to try and stop the Civil War, but it failed.
In 1861, Crittenden chaired the Frankfort Convention,
and he passed the Crittenden-Johnson Resolution, also called the War Aims Resolution,
to try to define goals for the Civil War.

The **Copperheads**, Peace Democrats, were opposed to the war when it began,
and they were led by Clement Vallandigham.
They were occasionally linked to the Knights of the Golden Circle,
and other leaders included Lambdin Milligan,
who was involved in the __Ex parte Milligan__ case.

==== Abraham Lincoln

Notably, we haven't really talked about **Abraham Lincoln** yet,
because he definitely deserves his own subsection.
Lincoln had grown up in Kentucky, and had moved to Illinois to become a lawyer.
He served in the Illinois House of Representatives, and was elected to the US House in 1846.
He opposed the Mexican-American War in his Spot Resolutions,
asking for proof of Mexican belligerence,
which made him unpopular in Illinois for a while.

In 1854, Lincoln joined the nascent Republican Party, helping it grow.
He gave the Peoria Speech against slavery and the Kansas-Nebraska Act, stating that
"`the policy of prohibiting slavery in new territory
originated with the author of the Declaration of Independence`".

In 1858, he ran for the Senate against Stephen Douglas,
in a race that contained lots of very public and famous debates.
His nomination acceptance is now called the House Divided speech, and Lincoln claimed that
"`I believe this government cannot endure permanently half slave and half free`".
Douglas formulated the Freeport Doctrine,
which said that states could always choose to outlaw slavery if they wanted to.

Lincoln lost the race, but later, he gave a speech at the Cooper Union university in New York,
once again asserting that he didn't think slavery should be expanded.
The speech helped him get the Republican nomination over William Seward.

The 1860 Presidential Election was Lincoln's next run for office, and he swept the North,
winning the election and becoming the 16th president.
When he was elected, seven slave states promptly seceded from the Union
and created the **Confederate States of America**.
Then, they attacked.

==== Events and Battles

===== Trent Affair

The United States risked battle with Great Britain when the U.S. Navy captured Confederate officers
off the RMS __Trent__.
Britain was particularly annoyed by this violation of neutrality,
and threatened to go to war with the U.S. over the affair.
Lincoln and his top advisers eventually decided to release the prisoners,
not wanting to damage Anglo-American relations.

===== Fort Sumter

The first shots were fired at Fort Sumter, where South Carolina troops assaulted the fort.
Commanders there included Abner Doubleday (baseball guy), Robert Anderson, and PGT Beauregard.
Mary Boykin Chestnut viewed the battle from The Battery,
and defenders at Fort Sumter were awarded the Gillmore Medal.

===== First Bull Run

The first __major__ battle was fought at the First Battle of Bull Run (First Manassas).
The Confederates under PGT Beauregard won the battle,
and General Bernard Bee reportedly said, "`There stands Jackson, like a stone wall!`",
giving **Stonewall Jackson** his nickname.
Irvin McDowell led the Union troops, who had issued retreating because of civilians in the way.
Important locations included Henry House Hill, Matthews Hill, and Brawner's Farm.
After the battle, the Pennsylvania Reserves were activated,
and the Confederate Army didn't pursue the Union because Bonham and Longstreet were having an argument.

===== Hampton Roads

At Hampton Roads,
the two ironclads USS **Monitor** and CSS __Virginia__ (formerly the **Merrimack**)
fought on the waters of the James River near Chesapeake Bay.
The Monitor's "`cheesebox`", its rotating turret,
was used to save the blockade and stop the Virginia.
Commanders at the battle include Franklin Buchanan (CSA) and the Swedish John Ericsson.

===== Shiloh

Also known as the Battle of Pittsburg Landing, Shiloh was a Union victory in southwest Tennessee,
resulting in the death of Albert Sidney Johnston.
On the first day, Union forces under Grant were pushed back,
the result of a surprise attack by Johnston and Beauregard,
but Grant's troops managed to fortify a bunker called the Hornet's Nest.
Troops under Stoney Lonesome and Lew Wallace became known as the "`lost division`",
because they took the Shunpike Road instead of the River Road,
and showed up too late to the battle.

Reinforcements for the Union showed up later, led by Bull Nelson and Don Carlos Buell.
A huge artillery unit led by Daniel Ruggles was assembled on Duncan Field.
At Fallen Timbers, Nathan Bedford Forrest (KKK) was shot while a rear guard.
Other notable locations include Owl Creek, a swamp pressured by Corinth Road.

===== Second Bull Run

Second Bull Run began at Brawner's Farm,
which had also been an important location in the first battle there.
Robert E. Lee's forces destroyed Union troops under John Pope,
and in the follow-up Battle of Chantilly, Isaac Stevens and Philip Kearny were killed.
After the battle, the Army of Virginia was dissolved,
and Robert E. Lee crossed the Potomac and started the Maryland Campaign.

===== Antietam

The bloodiest single day battle in US history, Antietam (Sharpsburg) was fought in Maryland in 1862.
The battle started when the Union army tried to capture Dunker Church, leading to a lot of losses.
Lee issued Special Order 191 (the "`Lost Dispatch`"),
a general movement order, which was recovered by Union troops;
the intelligence allowed the Union to figure out the Confederate strategy.

AP Hill brought reinforcements from Harper's Ferry for the Confederates,
and Ambrose Burnside captured a bridge (which was later named after him).
Multiple attacks were aimed at a "`sunken road`" that was known as Bloody Lane.
The battle allowed Lincoln to issue the Emancipation Proclamation.

===== Fredericksburg

At Fredericksburg, Robert E. Lee crushed Union troops under Ambrose Burnside in northern Virginia.
Lee had stopped the Union advance on Richmond at the Rappahannock River,
which Burnside's forces had to cross using pontoon bridges.
This let the Confederates set up artillery on Telegraph Hill and Howison Hill.
Edwin Sumner and William Franklin led attacks
that were repulsed by James Longstreet and Stonewall Jackson.

===== Chancellorsville

Chancellorsville was a "`perfect battle`" during which Lee defeated Joseph Hooker.
It took place simultaneously with the second battle at Fredricksburg,
and occurred when the Union crossed the Rappahannock.
During the battle, Stonewall Jackson was killed by friendly fire.
Confederates fortified Zoan Church during the battle,
which also featured fighting at Salem Church and Hanover Junction.

===== Vicksburg

Vicksburg was fought simultaneously with Gettysburg, in the west.
Grant's forces used David Porter's fleet to move northeast, and laid siege to Vicksburg, Mississippi.
He took Port Gibson, Grand Gulf, and Champion's Hill.
John Pemberton's Confederate forces had retreated to Vicksburg from Big Black River,
and Pemberton surrendered on July 4, 1863.

===== Gettysburg

The "`high water mark of the Confederacy`" came at Gettysburg, fought in the beginning of July 1863.
Union forces under George Meade defeated Lee (Lee's first defeat since Chancellorsville),
forcing him to turn back.
A few days before the battle, Joseph Hooker had resigned command of the Army of the Potomac.
Before the battle, the Battle of Brady Station was fought,
preventing JEB Stuart from fighting at Gettysburg.

Lots of important events occurred during the three day battle.
A boulder field called the Devil's Den was stormed by John Bell Hood and his Georgia troops.
Henry Heth fought John Buford near Cashtown, and attacked Union soldiers along Herr's Ridge.
Richard Ewell led a Confederate charge on the first day from the north, pushing Union soldiers onto a hill.
Other unsuccessful Confederate assaults included ones on Culp's Hill and Cemetery Ridge,
and other notable locations include Peach Orchard and Emmitsburg Road.

A lot of fighting also occurred at **Little Round Top** (there was also a Big Round Top).
Strong Vincent yelled "`Don't give an inch!`", before he was shot in defense of it.
A bayonet charge led by the 20th Maine, under Joshua Chamberlain, helped defend the position.
Other men who died at Little Round Top include Paddy O'Rorke and Charles Hazlett.

**Pickett's Charge** was an attempt by George Pickett
to get out of two hours of artillery barrage on Cemetery Ridge.
Along with Johnston Pettigrew and Isaac Trimble,
and his brigadier generals Richard Garnett and Lewis Armistead,
Pickett led a charge, but it didn't end very well.

===== Chickamauga & Chattanooga

In the west, the clearest Confederate victory was at the Battle of Chickamauga.
Braxton Bragg, along with Longstreet's corps from the east, defeated William Rosencrans.
During the battle, Union troops under George Henry Thomas helped defend Snodgrass Hill,
and Thomas was nicknamed "`the Rock of Chickamauga`".
Notable locations in the battle included Lafayette Road,
where the Union retreated to, and Horseshoe Ridge.
Longstreet exploited a gap in the right flank of the Union forces, breaking them.
After the battle, Union forces retreated to Chattanooga, which they had recently captured.

After Chickamauga, Union troops were besieged at the Battle of Chattanooga, and they won.
Defensive positions at Chattanooga included Lookout Mountain and Missionary Ridge.
After Chattanooga, Bragg was replaced by Joseph Johnston.

===== Mobile Bay

A Union naval victory at Mobile Bay
was able to close the last unblockaded port on the Gulf of Mexico.
Union ships were led by David Farragut, who may have said "`Damn the torpedoes, full speed ahead!`"
The major Confederate ship was the __Tennessee__, which was crippled by Farragut's forces.
Guns at Fort Morgan also helped the Confederates defend.
Other ships included __Tecumseh__ and __Chickasaw__,
which went to engage Fort Powell and Dauphin Island.

===== March to the Sea

In 1864, William Tecumseh Sherman led a March to the Sea through Atlanta,
and ending with the capture of Savannah.
On the way, troops bent railroad rails into "`Sherman neckties`" and tied them around things.
After capturing Atlanta, Sherman sent the "`Christmas gift`" telegram, giving the city to Lincoln.

===== Overland Campaign

The Overland Campaign started at the **Battle of the Wilderness** in 1864,
which took place a short distance from Chancellorsville.
It was fought in tangled woods, and lots of people died because of friendly fire and fire.
Longstreet and Hill went towards the Brock road, and Longstreet was wounded by friendly fire.

Longstreet wasn't able to fight in the following **Battle of Spotsylvania Court House**.
It was the bloodiest of the Overland Campaign, and it was fought near the "`Mule Shoe`",
which became called the "`Bloody Angle`".
At the battle, **John Sedgwick**, the highest ranking Union officer to die in the war,
was killed by a sniper after supposedly saying that those snipers
"`couldn't hit an elephant at this distance`".

===== Appomattox

A decisive Union victory at the Battle of Appomattox Court House
resulted in the surrender of the Confederacy.
Lee's Army of Northern Virginia surrendered to Grant's Union Army in the courthouse.
George Armstrong Custer was present at the battle,
and he bought some of the furniture in the courthouse.

==== Union Generals

===== George McClellan

McClellan was the first commander of the Army of the Potomac, during the Peninsular Campaign.
He lost the Seven Days Battles,
leading Lincoln to create the Army of Virginia and give **John Pope** command of it.
However, when Pope lost at Second Bull Run, McClellan was reinstated.

McClellan was extremely cautious, leading some to say he had a "`bad case of the slows`".
This didn't serve him well at Antietam, and cost him a decisive victory.
As a result, Lincoln pulled McClellan from command.

===== Ulysses S. Grant

Grant won some battles in the west, as discussed previously.
Then, he won at Appomattox and forced Lee to surrender.
Other details about Grant can be found when he becomes President.

===== Ambrose Burnside

Burnside was put in control of the Army of the Potomac
following McClellan's failure to pursue Lee after Antietam.
He had previously led a botched attack on a bridge at Antietam
-- the bridge will forever be called Burnside bridge.
Now, he's probably best known for the fact that his facial hair style is called "`sideburns`".

Burnside defeated Longstreet at Campbell's Station, and also won at Roanoke Island and New Bern.
He tried to blow a hole under Confederate lines at Petersburg,
an incident now called the Battle of the Crater.
After he failed miserably at Fredricksburg, Burnside was replaced as commander by Joseph Hooker.


===== George Armstrong Custer

Custer's most notable actions occurred after the war, but he did fight in the war as well.
While under Philip Sheridan,
Custer and his Wolverines had defeated Jubal Early in the Valley Campaigns.
At Gettysburg, he'd led cavalry to stop JEB Stuart from flanking the Union position.
He'd fought at Appomattox, and was given a table for his work at the Court House.
He was suspended from the army when he went to visit his wife, Elizabeth Bacon, in Fort Riley.

===== George G. Meade

Meade was the Union commander at Gettysburg.
After the Confederacy retreated, he didn't pursue them.

===== William Tecumseh Sherman

Sherman led the March to the Sea, capturing Atlanta and Savannah during the scorched earth campaign,
making Georgia "`howl`" during the march and giving Savannah as a Christmas present to Lincoln.
He issued Special Field Order No. 15, allowing for slaves to resettle after the campaign.
He was defeated at Kennesaw Mountain, and he also helped at Chattanooga.

He established Army Command at Fort Leavenworth, and he married Ellen Ewing
(daughter of **Thomas Ewing**, first Secretary of the Interior),
who said he suffered "`melancholy insanity`" when he was put on leave one time.
After Appomattox, Sherman met Joseph Johnston at Bennett Place to accept his surrender.

==== Confederate Generals

===== Robert E. Lee

The greatest of the Confederate generals was the commander of the Army of Northern Virginia.
Previously, Lee had captured John Brown at Harper's Ferry.
He had also led forces at the Battle of Cerro Gordo in the Mexican-American War,
outflanking the enemy by finding a trail that allowed Winfield Scott to circle around.
Notably, he said that "`It is well that war is so terrible, or we should grow too fond of it`",
while defending Marye's Heights.

Lee was given command
after Joseph Johnston was wounded right before the Seven Days Battles against McClellan.
He went on to win at Wilderness, Cold Harbor, Fredricksburg, and Chancellorsville.
He lost lots of men at Antietam, Cheat Mountain, and Gettysburg,
where he was forced back to the South.

===== Stonewall Jackson

Jackson had earned a promotion to major at the Battle of Chapultepec,
and he was a general by the time the Civil War rolled around.

At First Bull Run, Jackson held like a "`stone wall`" on Matthews Hill, giving him his nickname.
At the Battle of Gaines' Mill, Jackson showed up late,
and made a lot more mistakes during the Seven Days Battles.
He was defeated at the First Battle of Kernstown,
but during the Shenandoah Valley Campaign, Jackson won at Cross Keys and Port Republic.
He proceeded to take Harper's Ferry, and he held his lines at Fredericksburg.

At Chancellorsville, Confederate soldiers mistook Jackson for a Union soldier, and they shot him.
His arm was amputated, he got pneumonia, and died eight days later.

===== Joseph Johnston

Johnston was a pretty important commander in the Confederate Army.
After being wounded at the Battle of Seven Pines, command was given to Lee.

===== PGT Beauregard

Beauregard led the attack on Fort Sumter, and he was defeated at Shiloh by Grant's Union army.
He also won First Bull Run.
While besieged at **Corinth** by Henry Halleck,
he faked a counterattack and proceeded to lead his entire regiment out of the town unnoticed.

===== Braxton Bragg

At the Battle of Buena Vista in the Mexican-American War,
Bragg took control of a battery of "`flying artillery`" from Samuel Ringgold,
where he was told by Zachary Taylor to hold of Santa Anna's charge.

Bragg lost to Grant at Chattanooga, and he defeated William Rosencrans at Chickamauga.
He replaced Beauregard in 1862, and he commanded the II Corps at Shiloh.

===== John Bell Hood

Hood replaced Joseph Johnston at the defense of Atlanta from Sherman.
He lost at Nashville to George S. Thomas.
Hood also coordinated an invasion of Tennessee, led by Beauregard.

===== James Longstreet

Longstreet, Lee's "`Old War Horse`", was wounded at the Battle of the Wilderness.
He also led Pickett's Charge, albeit quite reluctantly, because it wasn't a very good idea.
After the war, he became a <<scalawag>>.
He helped calm civil unrest in New Orleans in 1875, and was later Ambassador to the Ottoman Empire.

===== JEB Stuart

Lee called Stuart the "`eyes of the army`".
He showed up late to Gettysburg, so he wasn't able to give Confederates very useful information.
He used to wear a cape and peacock-feature hat (which wasn't contemporary in the mid-19th century).
Stuart was killed at the Battle of Yellow Tavern.

=== Reconstruction

==== __Sic Semper Tyrannis__

**John Wilkes Booth** was an actor -- a Maryland native who sympathized with the Confederacy.
So, on March 20, 1865, Booth and some friends decided to kidnap the president.
He put together a group of friends
including John Surratt, Lewis Powell, George Atzerodt, and David Herold.
They met in a boarding house owned by Mary Surratt, John's mother.
They assembled when they thought Lincoln would be attending a play on March 17,
but Lincoln's plans changed and he didn't show up.

On April 14,
Lincoln and first lady Mary Todd went to a performance of __Our American Cousin__,
which was being shown at **Ford's Theatre**.
Booth decided to kill Lincoln that night, and he told Powell to kill Secretary of State Seward,
and assigned Atzerodt to Vice President Johnson's assassination.
Booth was well known at the theater, so he had free access to the whole building.
He walked into the presidential box and shot Lincoln in the back of the head.
He then stabbed Major Henry Rathbone and jumped down to the stage.
He shouted "`__sic semper tyrannis__`" (thus always to tyrants), and then ran away.

Booth then hid in Zekiah Swamp, and arrived back at Surratt's Tavern.
Along with Herold, he went and got help for his injured leg from Dr. Samuel Mudd.
Eventually, Booth was tracked down to the Garrett Farmhouse after his fellow conspirators,
and he was shot resisting arrest by Sergeant Boston Corbett.

The other assassinations didn't succeed.
Powell stabbed Seward in the face and neck, but he survived.
Atzerodt spent the evening drinking at a hotel bar and didn't try to kill Johnson.
Mary Surratt would become the first American woman to be executed.

==== Andrew Johnson

Johnson was governor of Tennessee during the Civil War,
and he had served in that post in the 1850s as well.
He became the only senator from the South that didn't leave the Senate after secession,
an act that led him to succeed **Hannibal Hamlin** as Lincoln's Vice President.
Before his first speech as Vice President, he'd apparently gone through a bottle of whiskey,
resulting in this bit of fun:

[quote]
  I am a-goin' for to tell you here to-day;
  yes, I'm a-goin for to tell you all, that I'm a plebeian!
  I glory in it; I am a plebeian!
  The people -- yes, the people of the United States have made me what I am;
  and I am a-goin' for to tell you here to-day -- yes, today, in this place --
  that the people are everything.

Following Lincoln's assassination, Johnson was inaugurated as the 17th president.

In an 1866 campaign against Radical Republicans,
Johnson delivered the Swing Around the Circle Speeches,
following a National Union Party convention in Philadelphia.
Johnson was joined by David Farragut and U.S. Grant.

Johnson's Secretary of State, **William Seward**,
negotiated the purchase of Alaska from the Russians.
In the Treaty of Cession negotiated with Baron Eduard de Stoeckel, called "`Seward's Folly`",
the US paid $7.2 million to Russia
in exchange for a territory that was nothing more than rocks and ice.
The Senate voted in favor of it
partly because of a speech given by Charles Sumner (of caning fame) in its favor,
and party because of the help of Cassius Clay (no, not that one).
Baron Stoeckel bribed the Daily Morning Chronicle to ensure that the paper supported it as well.
Because of the purchase, the calendar changed from the Julian to the Gregorian,
resulting in the date instantaneously changing from June 6 to June 18
(time travel in the 19th century).

The Senate didn't really like Johnson, so they passed the **Tenure of Office Act** over his veto.
The Act stated that Senate approval was needed to remove a Senate-confirmed official
(read: cabinet member) from office.
Johnson promptly tried to remove **Edwin Stanton**, his Secretary of War, from office,
and replace him with Lorenzo Thomas.
Of course, this was a violation of the Tenure of Office Act and Johnson was impeached.
The Swing Around the Circle speeches were cited as being "`disrespectful`" by the Senate,
and proponents of impeachment included John Bingham and Thaddeus Stevens.

==== Rebuilding the South

The South was in shambles after the war, and it had to be reconstructed.
Reconstruction began under Lincoln and continued until about 1877.

In 1864, the **Wade-Davis** Bill was written by two Radical Republicans.
It required Southern states who wanted to be admitted back into the Union to take an Ironclad oath,
stating that they had never supported the Confederacy.
The bill was pocket vetoed by Lincoln, who instead supported the **Ten Percent Plan**.
Lincoln's plan was more lenient,
only requiring that 10% of the vote count from a state had to swear an oath to the Union.

[[scalawag, scalawag]]
Lots of Northerners came South in an attempt to profit.
Because of their luggage, angry Southerners called them **carpetbaggers**.
Southerners who tried to do the same thing
and sympathized with the North were referred to as **scalawags**.

The **Freedmen's Bureau** was an organization that helped former slaves get an education.
It was headed by Oliver Howard, and it was created a couple months before Lincoln was shot.

==== Ulysses Grant

In 1868, **Ulysses S. Grant** was elected President.
His running mate was Schuyler Colfax, and he defeated Democrat Horatio Seymour.
The election had made an issue of Grant's General Order No. 11, which expelled Jews from some states.
He implemented the Force Acts to prosecute the Ku Klux Klan.

Grant's administration was full of scandals and scams.
During the Virginius Affair, there was a dispute over a ship in Cuba during the Ten Years' War.
His War Secretary **William Belknap** was accused of taking kickbacks from Caleb Marsh,
as a result of appointing Marsh to Fort Sill;
Belknap resigned pending impeachment.

On September 24, 1869, a day known as **Black Friday**,
**Jay Gould** and **James Fisk**
tried to corner the gold market on the New York Gold Exchange.
Other participants included Abel Corbin, who helped Fisk and Gould talk to higher social circles,
allowing them to give loans to people like Daniel Butterfield.
Eventually, the attempt was stopped by George Boutwell.

The **Whiskey Ring** was a scandal in which people tried to get around taxes on whiskey.
It was organized by John McDonald,
apparently under direction from Grant's private secretary Orville Babcock.
Babcock was eventually acquitted, but only because of his position so close to Grant.
Over 200 other people were indicted, including IRS agents such as John Joyce.
The scandal was uncovered by Treasury Secretary Benjamin Bristow.

During the **Credit Mobilier** of America scandal,
Oakes Ames offered discounted stock to congressmen
during the construction of the Transcontinental Railroad.
The scandal was investigated Aaron Perry,
and it was leaked when Colonel Henry S. McComb leaked letters to Charles Dana of the New York Sun,
who ran the "`King of Frauds`" column about the scandal.
Other people implicated in the scandal included James Patterson and James Brooks.

==== Post-War West

The first **Homestead Act** had been passed in 1862,
giving people who wanted to move West cheap land.
People who wanted to take up the government on its land offer simply had to be the head of a family
and not have taken up arms against the US.

**George Custer** went west,
trying to find gold in the Black Hills of South Dakota with Alfred Terry.
He led a campaign against Sioux in the area, destroying Black Kettle's home.
At the **Battle of Little Big Horn**, Custer fought the Sioux.
The chief was **Sitting Bull**, and the battle commander was **Crazy Horse**.
After Custer's last stand at Little Big Horn,
the only survivor of his forces was a horse named Comanche.
