== American Imperialism

[quote.epigraph, Theodore Roosevelt, 1899]

  I should welcome almost any war, for I think this country needs one.


=== A Gilded Age

Mark Twain coined the term **Gilded Age**
to talk about the fact that there were some pretty bad social problems
in the late 19th century, but they were masked by economic growth.

==== Rutherford Hayes

The Election of 1876 was one of the most controversial elections ever.
Republican **Rutherford B. Hayes** was up against Democrat **Samuel Tilden**,
who won the popular vote.
Tilden had been the Governor of New York, where he'd tried to stop Tammany Hall and Boss Tweed.
Hayes was down by 19 electoral votes,
but Florida, Louisiana, South Carolina, and Oregon were in dispute.
An elector in Oregon was declared illegal and replaced.
As a result, the **Compromise of 1877** was created, giving all 20 remaining votes to Hayes.
In return, Republicans agreed to end Reconstruction and take the troops out of the South.
Power in the South went to eh Democratic **Redeemers**,
and Hayes was sometimes called "`His Fradulency`".

Hayes's First Lady was **Lucy Hayes**,
now known as "`Lemonade Lucy`"
because she was a big supporter of the **temperance movement** to ban alcohol.
The president banned alcohol from the White House while in office.
Hayes's Secretary of the Interior was Carl Schurz, who helped determine Indian policy,
and his Attorney General was Carl Devens.
His Treasury Secretary was John Sherman,
and his Vice President was William Wheeler
(Hayes apparently asked "`Who is Wheeler?`" when told about his running mate).

Hayes vetoed the **Bland-Allison Act**,
in which the Treasury would be required to put $2 million in silver into circulation,
but Congress passed the act over his veto anyway.
He also sent Winfield Scott Hancock to Pittsburgh and Baltimore
to deal with the Great Railroad Strike.
Hayes removed Alonzo Cornell and Chester Arthur from power in the Port of New York,
an action that was opposed by his nemesis Roscoe Conkling, leader of the Stalwarts.

Hayes also helped arbitrate the end of the War of the Triple Alliance in South America.
He got Paraguay some territory.

==== Garfield and Arthur

Hayes didn't run for reelection, and Republican **James Garfield** took office,
having gotten the nomination as a result of a compromise with the Stalwarts and Half-Breeds.
Garfield had previously won Ex Parte Milligan,
and his rags-to-riches story was written by **Horatio Alger**.
While in office, Garfield had Postmaster General Thomas James investigate the Star Route frauds.

In 1881, **Charles Guiteau**, a Stalwart, asked Garfield for a consulship in Paris.
He had printed lots of copies of a speech
about Winfield Scott Hancock called "`Garfield vs. Hancock`".
Garfield refused Guiteau and Guiteau got angry.
Yelling "`I am a Stalwart!`", Guiteau shot Garfield.
In an attempt to help Garfield,
**Alexander Graham Bell** brought a metal detector to find bullets,
although at first it was only detecting springs in the bed that Garfield was on.
Garfield died and Guiteau was convicted of his murder,
and the assassination resulted in the Pendleton Civil Service Act being passed.

Garfield's Vice President **Chester A. Arthur** took office.
Arthur had previously been supported by Stalwart Roscoe Conkling (during the Hayes administration).
He signed the Pendleton Act, and he rebuilt the navy.
During Arthur's administration, the Chinese Exclusion Act was passed,
and he signed a compromise tariff called the Mongrel Tariff.
He also signed the Edmunds Act, banning polygamists from taking public office.

==== Cleveland, Harrison, and Cleveland

In 1884, **Grover Cleveland** was elected the 22nd president,
defeating Republican **James G. Blaine**.
Interestingly, during the election, Cleveland was supported by the **Mugwumps**,
Republicans who believed in Cleveland's ideas on civil service reform.
Cleveland (along with Tilden before him) was a **Bourbon Democrat**,
a conservative group of Democrats who wanted a gold standard.
Reverend Samuel Burchard claimed at a meeting where Blaine was present that
the Democratic party's antecedents were "`Rum, Romanism, and Rebellion`",
a fatal mistake during the last week of the campaign that hurt Blaine with the Catholic vote.

While he was in office, Cleveland refused to pay attention to the Tenure of Office Act,
which led to it being repealed in 1887.
His Vice President, Arthur Hendricks, died in 1885,
and during much of his term, Cleveland didn't have a Vice President.
He tried to reduce the amount of silver backing the dollar, favoring the gold standard instead.
His Secretary of State, Thomas Bayard, negotiated for fishing rights off of Canada,
and Cleveland withdrew the US from the Berlin Conference Treaty (recall the Scramble for Africa).
He also set the record for most vetoes in one term because he opposed spending so much.

During the election of 1888, Cleveland ran for reelection against **Benjamin Harrison**,
grandson of William Henry Harrison.
Harrison's campaign manager William Dudley tried to bribe "`the Blocks of Five`",
electors who sold their votes to Harrison.
Harrison won on issues like tariffs, leaving Cleveland a private citizen for the next four years.

In office, Harrison tried to get more money backed by silver.
To this end,
his administration managed to pass the McKinley Tariff and the **Sherman Silver Purchase Act**
with the help of the Billion Dollar Congress.
Also during his administration, the **Sherman Antitrust Act** was signed into law.
During the Baltimore Crisis, some American sailors were attacked by a Chilean mob.
He tried to help secure voting rights to enforce the 15th amendment in the Force Bill,
with help from Henry Cabot Lodge.
He did that in opposition to his Vice President, Levi Morton, but it mostly failed.

Harrison was nominated for reelection again, and went up against Cleveland again in 1892.
In the "`cleanest, quietest`" election of the post-war generation,
Cleveland defeated Harrison, making Cleveland the 24th president as well.
The victory might be attributed to the fact
that Harrison didn't campaign much because his wife had tuberculosis.

Cleveland took office again, and the **Panic of 1893** promptly began.
The increased coinage of silver had resulted in a gold shortage,
and Cleveland tried to get the Sherman Silver Purchase Act repealed.
The repeal of the act was the beginning of the end for silver as a basis for currency in the US.
In 1894, Cleveland also had to handle the **Pullman Strike**,
and he sent federal troops to break it up.
Also, while Cleveland was president, the Statue of Liberty showed up in New York.
He elevated the Department of Agriculture to the Cabinet, and he vetoed the Texas Seed Bill.

==== The Frontier: Wars with the Apache

American military influence in the southwest United States
and northern Mexico in the middle of the eighteenth century
resulted in increased resistance by numerous Native American tribes including the Chiricahua Apache.
Most notable among the war leaders of the movement was **Cochise**,
a chief who began an uprising in 1861 following the death of his father-in-law Mangas Coloradas.
Cochise hid in the Dragoon Mountains
and led raids against American forces led by General George Crook.
Cochise then worked on peace talks with **Otis Howard**,
the commissioner of the Freedmen's Bureau,
and Thomas Jeffords, perhaps the only white friend he had.

Following Cochise's death in 1874, **Geronimo** took over the fight for the Apache.
Some of Geronimo's followers were killed at Casa Grande in 1873,
and after he took over the fight, Crook sent multiple columns of troops into Mexico.
In 1886, Geronimo entered peace talks with Crook in the Canon de los Embudos.
However, on finding out that Crook was planning to kill him anyway, Geronimo escaped.
Crook was promptly replaced by **Nelson Miles**,
who ended up capturing Geronimo in Skeleton Canyon later in 1886.

Geronimo spent quite a while in captivity, mostly in Fort Sill.
During this time, he joined the Dutch Reformed Church to try and take the "`white man's road`",
but he was expelled after a few years because of his gambling habits.
Geronimo died in 1909.
His name is still used by jumping paratroopers.

=== Spanish-American War

==== William McKinley

McKinley had put the McKinley Tariff through Congress while Harrison was president,
although it had gotten replaced by the Wilson-Gorman Tariff.
He'd also chaired the Ways and Means Committee during the Billion Dollar Congress.
In 1896, he got himself the Republican nomination for president,
with the help of his strategist Mark Hanna.
He defeated **William Jennings Bryan**
after a front-porch campaign for the gold standard and "`sound money`".

McKinley passed the Dingley Tariff and in 1900, he set up the Gold Standard Act.
In 1898, the US annexed Hawaii and it became a territory.

In 1900, McKinley defeated Bryan again to get reelection.
However, he didn't stay in office very long.
In 1901, he went to the Pan-American Exposition in Buffalo.
Leon Czolgosz, an anarchist, came in concealing a pistol in a handkerchief.
Czolgosz shot McKinley, and failure to use a nearby X-ray machine may have contributed to his death.
Afterwards, Czolgosz claimed that his name was "`Fred Nobody`"
and said that "`I didn't believe one man should have so much service, and another man have none.`"

==== Course of War

The **Spanish-American War**, a splendid little war,
started in 1898 and was an important part of McKinley's presidency.
Cuba had been revolting against Spain for quite some time.

Eventually, the **USS Maine**,
under the command of Charles Dwight Sigisbee, exploded in Havana harbor.
People didn't know what was going on,
but **yellow journalists** like **Joseph Pulitzer** and **William Randolph Hearst**
helped people figure out that the Spanish were evil ---
"`Remember the Maine! To hell with Spain!`".
In 1976, the explosion would be investigated by Admiral Hyman Rickover,
and it was probably caused by a coal explosion, not a mine.

Also at time, Senor Don Enrique Dupuy de Lome sent the **De Lome Letter**.
The letter, sent to the Foreign Minister of Spain, Don Jose Canelejas,
was a huge insult to McKinley,
filled with references to his effeminacy and his ineffective weakness as a leader.
Hearst called it the "`worst insult to the United States in its history`".
Two months later, McKinley asked Congress to declare war.

The short war began in the Pacific.
At the **Battle of Manila Bay**,
the Asiatic Squadron, under Commodore **George Dewey**,
forced the Spanish Pacific Squadron, under Admiral Patricio Montojo,
to surrender the city of Manila.
American ships took position in Subic Bay, and the Spanish set up in Bacoor Bay.
Dewey spent the battle on the USS __Olympia__ and said "`You may fire when ready`".

A notable unit in the American army during the war was the 1st United States Volunteer Cavalry,
also called the **Rough Riders**,
or "`Wood's Weary Walkers`" after their commander, Leonard Wood.
Wood's second in command was **Theodore Roosevelt**, former assistant Secretary of the Navy.
When Wood left the regiment, the Rough Riders became Roosevelt's.
They fought at the Battle of Las Guasimas,
and at the **Battle of San Juan Hill**, near Kettle Hill.
San Juan Hill was an important battle for the Rough Riders.
Henry Lawton's men were stopped at the Battle of El Caney,
so Wood was forced to charge up the hill against Arsenio Linares.
Other locations in included Bloody Ford and Hell's Pocket.

The war was ended by the **1898 Treaty of Paris**.
Spain gave up control of much of its land,
and the US got temporary control of Cuba
and indefinite control of Puerto Rico, Guam, and the Philippines.
Following the treaty, the Insular Cases decided that in the island territories,
"`the Constitution follows the flag`".

=== Progressivism and Imperialism

==== Organizing Labor

Poor labor conditions in the early nineteenth century
resulted in the creation of the **Knights of Labor** in 1869.
Led by Grand Master Workmen such as Uriah Stephens and **Terence Powderley**,
the Knights were the first large labor organization in the United States.
Members of the union killed many Chinese laborers in the 1885 **Rock Springs Massacre**,
and they attempted a strike against Jay Gould's Great Southwest Railroad in 1886.

On May 1, 1886,
anarchists threw a bomb at police officers in **Haymarket Square** in Chicago
during a strike against the McCormick Harvesting Machine Company.
The ensuing riot resulted in many arrests,
as well as the executions of August Spies and three other men.
Governor **John Peter Altgeld** ended up pardoning everyone else,
but the Knights of Labor were blamed for the incident and their reputation was irredeemably damaged.

This paved the way for the rise of the **American Federation of Labor**,
led by **Samuel Gompers**.
The AFL was created primarily as a place for people dissatisfied by the Knights of Labor,
and they excluded unskilled workers, African Americans, and women.

==== Women's Suffrage

In order to discuss the history of women in the United States,
we must begin some time ago.
In the early and middle parts of the nineteenth century, the **cult of domesticity** emerged.
Thus arose the notion that ideal women stayed with the house and did not work outside it,
as a result of the fact that people didn't all need to work on making goods by themselves to survive.
Even at this time, there were some minor equality movements,
but they were largely unsuccessful,
and many of them were tied to abolitionism.
Notably, Oberlin College became the first coeducational institution in 1837,
just four years after its founding.

The **first wave of feminism** started at the **Seneca Falls Convention** in New York in 1848.
Organized by **Elizabeth Cady Stanton** and **Lucretia Mott**,
the convention put forth a **Declaration of Sentiments**, which stated that
"`all men and women are created equal`".
Stanton and Mott had come up with the idea eight years previously,
while attending William Lloyd Garrison's World Anti-Slavery Convention.
It is also notable that Frederick Douglass argued in favor of women's suffrage at the convention.

Three years later, Stanton met **Susan B. Anthony**,
and together, they founded the New York Women's State Temperance Society, as well as the Women's Loyal National League.
In 1868, Anthony began a women's rights newspaper called __The Revolution__,

In 1872, Anthony was arrested for voting in Rochester, New York,
and although she was convicted, she never paid the fine.
Later, she and Stanton presented Congress with what would become the 19th Amendment.
In 1890,
she united women's rights activists into the National American Woman Suffrage Association (NAWSA).

The 19th Amendment passed Congress in 1920, granting women the right to vote.

==== Theodore Roosevelt

Under William McKinley, Roosevelt had served as Assistant Secretary of the Navy,
and he'd led the Rough Riders for a year in the Spanish-American War.
Coming back from the war, he became Governor of New York,
but party establishment didn't want him actually doing anything,
so they put him in the least powerful position in government: the Vice Presidency.
However, McKinley's assassination led to Roosevelt being sworn in as the youngest president in history
when he was just 42 years old.

As president, Roosevelt put forward his **Square Deal** domestic policy.
His vice president was Charles Fairbanks.
He tried to make life more fair for people by "`trustbusting`",
and helping reform with the Pure Food and Drug Act.
He coined the term "`bully pulpit`" for the power he wielded from the White House.
He also passed the Elkins Act, fining railroads offering rebates.
Roosevelt led the country into the new **Progressive Era**.
In 1904, he was reelected over Alton B. Parker in a landslide.
He loved the outdoors, and established many new national parks, forests, etc.
Roosevelt was also a historian;
he wrote __The Naval War of 1812__ and __The Winning of the West__.

Roosevelt's foreign policy was all about "`speaking softly and carrying a big stick`".
He sent the new **Great White Fleet** all around the world to show that the US was powerful.
His Corollary to the Monroe Doctrine, proposed after the Venezuela Crisis (British bombarding Venezuelan forts),
stated that the US will intervene in cross-hemisphere conflicts between Europe and Latin America to ensure fairness.
He set up a Gentlemen's Agreement to prevent Japanese immigration.

==== A Man, A Plan, A Canal, Panama

In the late 1690s,
the Scots had tried to connect the Atlantic and Pacific Oceans using the Darien Scheme;
they wanted to make a colony providing an overland route across Panama.
That didn't work out.

In the early 20th century, the first people to try and make a canal through Panama were the French.
They failed badly, and the company's director **Philippe Bunau-Varilla**,
came to Washington asking for help from Roosevelt and Secretary of State **John M. Hay**.
The Senate voted in favor of building the canal across the isthmus, but there was a problem.
Panama wasn't its own country; rather, it was part of Colombia, and they didn't want the canal made.

The Hay-Herran Treaty was proposed by US to mitigate this issue,
but the Colombian Senate didn't like it.
Bunau-Varilla told the Americans that the Panamanians might revolt soon,
in an effort to get their __own__ dictator,
and Roosevelt decided to actively support the rebels.
Dr. Manuel Amador worked with the Americans brought by the USS __Nashville__,
overthrew the Colombian government, and became the first president of an independent Panama.

After the revolution was successful,
Bunau-Varilla signed the **Hay-Bunau-Varilla Treaty** with the US,
giving them rights to dig across the isthmus.
Notably, no Panamanians actually signed the treaty.
Roosevelt, faced with a bit of an image problem as a result,
was told by Attorney General **Philander Knox**:
"`Mister President, do not let so great an achievement suffer from any taint of legality!`"
Construction on the Panama Canal would proceed from 1904 to 1914.

==== William H. Taft

Roosevelt decided not to run for reelection again in 1908.
He endorsed Secretary of War **William Howard Taft** for the presidency instead.
Taft had been the first American Governor-General of the Philippines.
After the Russo-Japanese War,
he'd discussed the Taft-Katsura Agreement with the Japanese Prime Minister.

As president, he tried to improve the economies of Latin America with **Dollar Diplomacy**.
His Secretary of State was Philander Knox,
and his Secretary of the Interior, Richard Ballinger,
had an argument with the Forestry Service under Gifford Pinchot (Ballinger-Pinchot affair).
In 1909, the **Payne-Aldrich Tariff** was passed.
The tariff was really high and protectionist, so it was unpopular;
Taft defended it in the Winona Speech,
and he claimed it was the "`best tariff bill that the Republican Party ever passed`".

Taft was really fat, and he may or may not have gotten stuck in a White House bathtub at some point.
He would go on to become the only President to also serve as Chief Justice of the Supreme Court.

==== Election of 1912

The election of 1912 heralded the return of Theodore Roosevelt from his badly timed four year leave.
He formed the Progressive **Bull Moose Party** instead of being nominated by Republicans again,
since they picked Taft as their candidate again.
Democrat **Woodrow Wilson** was nominated after a fairly contentious Democratic convention,
and he picked Oscar Underwood as his running mate.
The fourth candidate was Socialist **Eugene V. Debs**,
who ended up getting 6% of the popular vote.

Roosevelt's reforms were grouped together as "`New Nationalism`" and advocated a strong government;
Wilson's "`New Freedom`" platform was based on a smaller government.
Taft didn't use a fun name like Roosevelt and Wilson, and he came in third in the election anyway.
In 1912, Roosevelt was shot by John Schrank on the campaign trail,
but the bullet was sufficiently slowed down
by his eyeglass case and his 50 page speech that he said:

[quote]
  Friends, I shall ask you to be as quiet as possible.
  I don't know whether you fully understand that I have just been shot;
  but it takes more than that to kill a Bull Moose.
  But fortunately I had my manuscript,
  so you see I was going to make a long speech, and there is a bullet
  --- there is where the bullet went through ---
  and it probably saved me from it going into my heart.
  The bullet is in me now, so that I cannot make a very long speech, but I will try my best.

The split Republican vote allowed Wilson to win the election.
Taft only won 8 electoral votes,
and the election was the first and only time since 1860 that 4 candidates cleared 5% of the vote.

