== Recent European History

[quote.epigraph, Charles de Gaulle]

  The better I get to know men, the more I find myself loving dogs.


=== Republics of France

==== Fourth Republic

On October 13, 1946, a new **Fourth Republic** established itself in France.
The French Colonial Empire proceeded to fall apart.
French Indochina was lost at the Battle of **Dien Bien Phu**,
falling into Viet Minh hands, led by <<ho-chi-minh, Ho Chi Minh>>.

In 1956, France faced the **Suez Crisis**.
France had built the Suez Canal, and therefore owned the Canal.
When Egyptian President **Gamal Abdel Nasser** (more in the later chapters)
decided to nationalize the Canal, Britain and France attacked.
Isreal had also allied with Britain and France in the secret Protocol of Sevres.
It started when Israel, aiding the British and French, began Operation Kadesh.
They invaded Port Said as part of Operation Musketeer.
Eisenhower would put a stop to the fighting.

==== President de Gaulle

Shortly after the Suez Crisis, Guy Mollet was forced out of the post of Prime Minister.
By 1958, the Fourth Republic was falling apart under Rene Coty.
French army units took power in Algiers in May and the whole thing fell apart.

Into this crisis rose **Charles de Gaulle**, who had led the Free French in World War II.
The National Assembly put de Gaulle in power and he founded the new **Fifth Republic**.
He introduced his "`Politics of Grandeur`"
and demanded that France be given complete autonomy in its affairs.
He withdrew France from NATO's military command,
because he thought that the US had too much control.
In 1965, de Gaulle helped start the Empty Chair Crisis,
which involved financing the Common Agricultural Policy of the European Economic Community (EEC).
The crisis was resolved when the Luxembourg compromise was reached in January 1966.

On a visit to Canada in 1967, de Gaulle voiced support for a free Quebec,
declaring, "`vive le Quebec libre`" (long live free Quebec).

The new president also had to deal with the war in Algeria.
After visiting Africa, he decided that he supported independence for Algeria,
and neutralized the army that was stationed there.
In 1959, he gave the country self-determination,
and there followed a revolt by the French settlers.
The Secret Army Organization opposed Algerian independence.

In 1962, de Gaulle signed the **Evian Accords**,
creating a ceasefire in Algeria and giving victory to the FLN
(National Liberation Front in Algeria).
This resulted in several assassination attempts against him by the OAS
(the settlers' resistance group),
including one in which he narrowly escaped machine gun fire in a limousine.

In May 1968, protests broke out against de Gaulle's government.
His OTRF broadcasting organization had a monopoly on TV and radio.
On May 29, de Gaulle disappeared without telling anyone.
He went to Baden-Baden, from whence he returned with the military's support.
During the revolts, the Grenelle Agreements were signed, increasing the minimum wage,
but failing to resolve the conflict.
Eventually,
de Gaulle's time as a leader was up and **George Pompidou** took over running the country.

=== United Kingdom: The Commonwealth

Many important things happened between the end of the Second World War and the late 1960s,
but I'm not going to talk about them.

**The Troubles** started in 1968
as a conflict between republicans and unionists in Northern Ireland.
They started when a series of riots such as the Battle of the Bogside broke out in Derry.
During the Troubles, ten inmates at Maze Prison, including Bobby Sands,
starved themselves to death.
The Troubles were ended by the **Good Friday Agreement** in 1998,
which came about as the result of peace talks chaired by George Mitchell.

In the 1970s, the UK went through some rough economic times.
Labour had returned to power in 1974 under Harold Wilson.
The economy got worse until Wilson was replaced by James Callaghan.
But, he presided over the Winter of Discontent and he was voted out with no confidence.

In 1979, Conservative **Margaret Thatcher**, the Iron Lady, was elected prime minister.
Philosophically,
Thatcher held views similar to Ronald Reagan and Brian Mulroney (elected in Canada in 1984).
Her Conservative Party was made up of "`wets`" and "`dries`".
After the Maze Prison hunger strike, Sinn Fein started to come back into power.
In 1981, the royal family was brought back into the limelight when
**Prince Charles** married **Princess Diana**, and everyone cared.

In Argentina, an unstable military junta under Leopoldo Galtieri had taken power.
On April 2, 1982, Argentina invaded the British-controlled Falkland Islands,
starting the **Falkland War**.
In response, the British sent a naval task force to the islands.
They opened with the Black Buck Raids and the Raid on Pebble Island,
and proceeded to try Operation Mikado, which was aborted.
After an amphibious landing at Port San Carlos, they won the Battle of Goose Green.
A big chunk of Argentine casualties occurred when the British sunk ARA __General Belgrano__.
The British used Ascension Island as a staging ground, where they used US technology.
The whole war lasted over seventy days,
and resulted in British victory and restoration of the status quo.

In other foreign affairs, Thatcher visited Deng Xiaoping in China
and negotiated the peaceful transfer of Hong Kong back to China in 15 years.
She also set up the creation of Zimbabwe from the former state of Rhodesia.

At home, Thatcher faced a National Union of Mineworkers strike led by Arthur Scargill.
During the Westland affair,
Thatcher and her Defence Minister Michael Heseltine
dealt with the rescuing of Westland Helicopters.
The incident embarrassed the government,
hurt Thatcher's public reputation, and led to Heseltine's resignation.
At one point, she survived an IRA assassination attempt by Patrick Magee and his men
in which they tried to blow her up in the Grand Hotel in Brighton.
When she tried to institute the Community Charge (essentially a poll tax)
her popularity vanished and she was replaced by **John Major**.

=== Eastern Bloc

==== Czechoslovakia

After World War II, Czechoslovakia expelled a bunch of Germans who'd been living in its borders.
The Third Republic began, but the country became part of Stalin's sphere of influence.
In February 1948, Communists took over the country, and Edvard Benes came to power.
In June 1953, strikes in Plzen were broken up without too much blood,
disappointing Allen Dulles,
who'd wanted an excuse for the CIA to help the people resist Soviet control.
The 1960 Constitution proclaimed the victory of socialism,
and created the Czechoslovak Socialist Republic.

[[prague-spring, Prague Spring]]
In January 1968, **Alexander Dubcek**, a Slovak reformer,
was elected first secretary of the KSC (Communist Party of Czechoslovakia).
He replaced Antonin Novotny as Novotny also ceded the presidency to Ludvik Svoboda.
Dubcek started to enact a new reform movement in the spring of 1968,
which would be known as **Prague Spring**.
On April 5,
he set up the Action Programme, which guaranteed freedom of religion, press, assembly, and speech,
calling it "`socialism with a human face`".
During Prague Spring, Ludvik Vaculik published his "`Two Thousand Words`" manifesto.
Other Warsaw Pact countries weren't particularly happy about what was happening in Prague Spring,
so they invaded Czechoslovakia in August.
Dubcek was arrested and taken to Moscow, where he negotiated the **Brezhnev Doctrine**,
allowing for Czechoslovakia to become partially sovereign, with the KSC gaining power.
Notably, in January 1969,
Jan Palach set himself on fire in Prague to protest the invasion of the country
and the end of Prague Spring.
By April 1969, Dubcek was replaced by **Gustav Husak**.

Skip forward a bit to 1989, when the anti-Communist revolution started.
Between November and December of that year,
the non-violent **Velvet Revolution** took place.
The main anti-communist party was Charter 77,
a civic initiative that managed to overthrow the communist regime.
Former playwright **Vaclav Havel**
was elected the first president of Czechoslovakia in 41 years.
Havel was reelected and became the first president of the new Czech Republic,
after it split from Slovakia following the Velvet Divorce in 1993.

==== Communism in Hungary

After the war, Hungary had passed a new constitution,
and socialism was set up as the main governmental goal.
The People's Front, led by Matyas Rakosi, took power and declared all other parties illegal.
In May 1949, Laszlo Rajk of the "`Hungarian`" Communists, was arrested and put on trial.
He was found guilty and executed,
and Rakosi proceeded to impose full totalitarian rule, executing thousands.
His secret police, led by Gabor Peter, persecuted anyone that Rakosi called an enemy.
Rakosi fell in 1956.

On October 23, 1956, a student demonstration in Budapest began.
The protests got attention from the police, who opened fire on the students,
sparking the **Hungarian Revolution of 1956**.
Stalin's statue was toppled, and people wanted Erno Gero to step down from power.
At two in the morning the following day, Soviet tanks entered Budapest.
On the 25th, they opened fire on protesters,
and the Central Committee forced Gero to resign, replacing him with **Janos Kadar**.
At this point,
**Imre Nagy** and a group of supporters took over the Hungarian Working People's Party.
Nagy freed Cardinal Josef Mindszenty, among other political prisoners.
On November 1, Nagy announced that he was going to withdraw from the Warsaw Pact.
Then, Khrushchev intervened.
Soviet tanks took airfields and subdued the Hungarian forces.
Nagy was arrested and replaced by Janos Kadar, a Soviet loyalist.

Kadar proceeded to lead an attack on the revolutionaries, imprisoning or killing them.
He then declared general amnesty.
By the late 1980's, Kadar's government was poised to become a Western-style democracy.
Kadar was replaced in 1988 by Imre Pozsgay.

==== Romania

Going back a bit, Romania had declared independence from the Ottomans in 1878,
following the Russo-Turkish war.
The country declared neutrality in World War I,
but was eventually pressured into joining the Allies.
Surrounded by Austria-Hungary and the Ottomans, most of the country was immediately captured,
but the Allied victory resulted in territorial gains.
The interwar years were characterized by the larger country they called "`Greater Romania`",
and in 1938, the first Romanian dictator, **King Carol II** came to power.

When World War II started,
the Soviet Union declared interest in Bessarabia, currently under Romanian control.
While Romania initially tried to remain neutral,
Soviet aggression led to the country joining the Axis Powers.
Territorial losses in the opening year of the war led to Carol II being deposed.
He was replaced by **Ion Antonescu** and the Iron Guard,
who formed the National Legionary State.
Antonescu and friends participated in the Holocaust,
and were deposed late in the war by **King Michael I**,
who decided to have the country join the Allies instead.

Three years later, in 1947, Michael was forced out of power by Communists.
Soviet occupation resulted in a communist republic governed by **Gheorghe Gheorghiu-Dej**.
With the death of Gheorghiu-Dej in 1965,
**Nicolae Ceausescu** became the first President of Romania.

Ceausescu's regime became increasingly authoritarian throughout the 1970s.
In his **July Theses** speech, Ceausescu aimed to intensify socialist ideology in the country,
beginning a Neo-Stalinist type attack on freedom and autonomy.

In December 1989,
Ceausescu tried to evict Laszlo Tokes, a Hungarian pastor, from the city of Timisoara.
Protests against the move quickly spiraled into a
**Romanian Revolution** against the regime in general.
People's opinion of the government dropped quickly,
and when Ceausescu tried to give another speech on the 21st,
the audience quickly booed him off the stage, yelling "`Timisoara!`"
Ceausescu took refuge in the Central Committee building with his wife Elena,
but the following day, the crowd rushed the building and made it inside.
He and his wife barely managed to escape by taking a helicopter off the roof.
On Christmas Day, the Ceausescus were arrested and killed.

==== Polish Republic

The Polish People's Republic was created under the communist Polish United Workers' Party,
and the new name was adopted in 1952.
Under the Stalinist regime, thousands were tried and executed.
The Catholic Church was persecuted after Stalin died,
Cardinal Stefan Wyszynski was detained,
and there was a show trial of the Krakow Curia in January 1953.
When the Warsaw Pact formed in 1955, the Polish People's Republic had the second largest army.

As de-Stalinization started in 1956, riots broke out in Poznan.
During the **Polish October**,
the new Polish Party's First Secretary **Wladyslaw Gomulka** liberalized life.
This Polish Thaw started the country in the "`way to socialism`".
During the 1968 political crisis, inspired in part by Prague Spring,
Polish opposition set up protests, prompting a crackdown by the authorities.

In the early 1970's,
Poland's economy was in a good place, but the 1973 oil crisis caused a recession.
Edward Gierek, who had replaced Gomulka, tried to help the economy, but he wasn't successful,
and 1976 led to protests against him.
In 1978, Cardinal Karol Jozef Wojtyla became **Pope John Paul II**, improving Catholic morale.
By 1979, economic growth was tanking and foreign debt was going straight up.

In 1980, the government tried to increase meat prices,
but that resulted in general strikes in Lublin.
Then, protests at the **Gdansk Shipyard**
started a reaction of strikes that stopped a lot of progress.
Workers led by **Lech Walesa**,
a former electrician who had led the strike at the Lenin Shipyard,
signed the Gdansk Agreement that ended the strike.
Now, a bunch of unionizing movements swept over the country.
On September 17, they got together in Gdansk, led by Walesa,
and created a new national union organization called **Solidarity**.
In 1981, at the first Solidarity National Congress,
Walesa was elected the national chairman of the Union.

In December,
the regime began martial law in the country, and ZOMO riot police were deployed to stop Solidarity.
The Military Council of National Salvation was put in charge,
as a basic appearance of political stability had been attained.
When Gorbachev came to power, his reforms helped Poland.
Then, the Round Table Negotiations and the election of 1989 led to the fall of communism.

The Round Table Agreement set up local self government,
and the legislature (the Sejm) was split based on the new agreement.
After some work, Lech Walesa was elected president of the Third Polish Republic in November 1990.

==== Yugoslavia

Yugoslavia had been created following the First World War,
when it was called the Kingdom of Serbs, Croats and Slovenes.
But they decided that name was too long, and in 1929 it was renamed to the Kingdom of Yugoslavia.
It was invaded during World War II,
and after the war, it was known as the Federal People's Republic of Yugoslavia.
A communist regime was put in place.

At the head of the country was the Partisan **Josip Broz Tito**.
Tito took down the Chetnik (opposing party) leader Draa Mihailovic,
and he set up the UDBA secret police.
Yugoslavia was expelled from Cominform in 1948 following Tito's notable **split with Stalin**,
and he became the First Secretary General of the Non-Aligned Movement,
which he helped created with Gamal Abdel Nasser and <<A New India, Jawaharlal Nehru>>.
Tito signed the Treaty of Vis with Ivan Ubaic, and his British liaison was Fitzroy Maclean.
After imprisoning Aloysius Stepinac for helping the Ustashi movement against him,
Tito was excommunicated by the pope.
In 1974, Tito called himself "`President for Life`",
promoting "`brotherhood and unity`" in Yugoslavia.

Tito died in 1980.
This led to some internal strife in Yugoslavia,
and the country dissolved by 1991, leading to the Yugoslav Wars.

==== Bulgaria

Bulgaria had joined the Axis in 1941 as part of the Tripartite pact,
occupying much of the Balkans (Greece, Yugoslavia).
However, when the Red Army marched across the border in 1944,
Bulgaria severed ties with the Axis
and the Communist Party in the country launched a coup and installed a new government led by the Fatherland Front.

By 1946, the monarchy had been abolished, Tsar Simeon{nbsp}II had been exiled,
and the Kingdom of Bulgaria became the People's Republic of Bulgaria.
The Communist Party, led by **Georgi Dimitrov**, became the majority power.

Dimitrov was succeeded on his death in 1949 by Vulko Chervenkov,
who wasn't popular enough to keep hold of power.
He was replaced by **Todor Zhivkov** in 1954,
who would remain General Secretary of the party until 1989
(making him the longest serving leader under the Iron Curtain).

Among the political complexities the Bulgarian government had to deal with was the matter of Pirin Macedonia.
A Macedonian region which had been ceded to Yugoslavia after the First World War,
its fate had been left to the whims of the relationship between Tito and Stalin.
Bulgaria and Greece had been fighting over Macedonia for many years,
but now Stalin demanded that cultural autonomy must be given to the people of Pirin Macedonia,
to create a unified identity within Bulgaria.
In the 1960s (well after Tito and Stalin stopped being friends),
Zhivkov would declare that Pirin Macedonia was part of Bulgaria,
stating that there was no such thing as a Macedonian nation,
and all accounts to the contrary had been fabricated by the Yugoslav government.

Zhivkov borrowed ideas from the Soviet Union and China,
being inspired by the Great Leap Forward to create the Third Five-Year Plan (1958-1962),
which attempted to industrialize and liberalize the country.
However, due to nearby turmoil (e.g. the USSR invading Czechoslovakia in 1968),
Bulgaria backed off on the aggressive industrial investment and began to stagnate in the 1970s.
Zhivkov tried to remedy this in 1981 using the "New Economic Model",
but the general quality of life stayed low as shelves stayed empty (or filled with mediocre products).

In 1980, the Zhivkov and the Bulgarian government, spurred by Turkey's invasion of Cyprus
and Kenan Evren's coup in Turkey in 1980,
decided to wage a culture war on the Turkish minority in Bulgaria.
Turks were forbidden to speak their language,
were forced to change their names,
and in 1989, the Turks were expelled from Bulgaria (resulting in yet more economic decline).

Zhivkov's failure to improve things came to the forefront,
and he was replaced with Peter Mladenov in 1989.
That only kept the Communists in power for a short time, though,
as proper elections were held in 1990,
ending the Communist lead in government and renaming the country the Republic of Bulgaria.

=== The Balkans

==== Bosnian War

I'm going to go a little further than I have in other sections.
The **Bosnian War** took place between 1992{n-}1995, in Bosnia and Herzegovina.
It came about as a result of the dissolution of Yugoslavia.
When Bosnia and Herzegovina declared independence,
the Bosnian Serbs, supported by **Slobodan Milosovic** and his Serb forces,
mobilized inside the country and started a war that raged across all of Bosnia and Herzegovina.

On one side was the Serb Army of the Republika Srpska (VSR),
and on the other was the Army of the Republic of Bosnia and Herzegovina (ARBiH).
Also in the mix were the Croats, who wanted to make parts of Bosnia and Herzegovina part of Croatia.

The war was full of fighting,
unchecked shelling of populated areas, ethnic cleansing, and mass rape.
These atrocities were especially exemplified by the Siege of Sarajevo
and the Srebrenica Massacre, during which Ratko Mladic's troops killed over 8,000 men and boys.
During the war, Sarajevo was home to Sniper Alley, a major street in the city,
where signs reading "`PAZI`" warned about the dangers inherent in using the road.
After the massacres, NATO forces intervened in 1995.
The war included Operation Deliberate Force and Operation Deny Flight,
and the latter resulted in the Banja Luka incident,
in which six Serb attack jets were shot down by American F-16s.

Peace negotiations in Ohio resulted in the **Dayton Agreement**,
which was finalized in November 1995.
The treaty that was signed by Alija Izetbegovic, Franjo Tuđman, and Bill Clinton.
