== Renaissance & Reformation

[quote.epigraph, Leonardo da Vinci]

  While I thought that I was learning how to live, I have been learning how to die.


After the Middle Ages, a rebirth of culture and achievement began.
It started in Italy, and it would provide a transition from Medieval Times into the Early Modern Era.

=== Italian Renaissance

The **Renaissance** started in Tuscany on the west coast of Italy.
It spread to Venice, where the **humanist** scholars were happy with the new discoveries,
and they enjoyed interest in the classics that had been forgotten in what they called the Dark Ages
(so named because light bulbs had not been invented yet).
The Italian Renaissance peaked in the 16th century
when the Italian Wars threw the region into turmoil.

We'll leave the numerous cultural achievements of the Renaissance
to literature experts and art historians.
Suffice it to say that there was a lot of very good stuff that came from the era,
including works of
Petrarch, Bocaccio, Michelangelo, Leonardo da Vinci, Botticelli, Raphael, Titian, etc.

==== Background

Remember that the papacy had been moved to Avignon by Philip the Fair,
so the papal states were fairly loosely held together, and didn't do a lot of huge things.
However,
the Fourth Crusade had done much to improve the strength of trade
of the northern Italian city-states, like Genoa, Venice, and Pisa, weakening the Byzantine Empire.

Most of the outside kingdoms left the city-states of Italy alone,
and Florence grew in strength,
resulting in their florin becoming the __de facto__ currency of trade.
Merchants were very powerful people in the 13th century.

But, in the 14th century, the economy fell apart, party as a result of the Hundred Years' War.
The banks of Bardi and Peruzzi in Florence collapsed.
The **Black Death** swept through Europe and took out nearly a third of Europe's people.
During the plague, **flagellants** went around whipping themselves for religious reasons.
Florentine textile workers rebelled in the __ciompi__ in 1378.

==== Warring City-States

Northern Italy was divided between city-states,
and there was conflict between the forces of the papacy and the Holy Roman Empire.
Internally, they were also divided between the factions of the **Guelphs and the Ghibellines**.
Mercenaries were employed by many city-states, and many would have a sizable military force.
On land, the mercenaries were called __**condotierri**__,
and they came from all over Europe.

Pisa, Genoa, and Venice fought many battles on water, and eventually Pisa's became weakened.
On land, Florence, Milan, and Venice became dominant,
and they signed the Peace of Lodi (1454) and agreed to stop fighting so much.

==== Florence

===== Medici Rule

For much of the 14th century, the House of Albizzi led Florence.
Florence became the central banking hub of Europe when Siena's Bonsignori banks failed.

The main family that rivaled the Albizzi was the **Medici**.
The first of the Medici was **Giovanni de' Medici**,
followed by his son, **Cosimo di Giovanni de' Medici** (Cosimo the Elder).
They controlled the largest bank in Europe,
so they had a lot of money and would stay in power for three centuries.
Cosimo had negotiated the Peace of Lodi with **Francesco Sforza**, leader of Milan.
Cosimo's son Piero succeeded him, and promptly died.

Power passed to Cosimo's grandson, **Lorenzo the Magnificent**.
Lorenzo would become a big patron of the arts, which was quite important in Renaissance Italy.
He formed the Council of Seventy,
which formalized rule of Florence with Lorenzo himself at the head.
However, his relationship with others slowly decayed, and the papacy didn't like him very much.
At the Castello del Trebbio,
the Pazzi family was nudged by Pope Sixtus IV to conspire against Lorenzo.
On April 26, 1478, they tried to kill Lorenzo after High Mass at the Santa Maria del Fiore
(the Florence Cathedral, the one with the big dome).
They managed to stab Giuliano, Lorenzo's brother, but Lorenzo escaped wounded.
Florentines took it upon themselves to kill off many members of the Pazzi family
(perhaps Ezio Auditore had something to do with it?)
and the Pazzis were forced out of Florence.

===== Bonfire of the Vanities

Near the end of the 15th century, **Girolamo Savonarola**, a Dominican monk,
took Florence after the French, led by Charles VIII, invaded the city.
Savonarola had prophesied a biblical flood from the north,
and people took Charles's invasion to mean that Savonarola was right.
He took power to combat the secularism that had been flourishing
(seeing how secularism doesn't really help monks),
and his followers were called the __Piagnoni__ (the "`Weepers`").

Savonarola destroyed a bunch of art and books in the Piazza della Signoria
during his **Bonfire of the Vanities**,
notably making Sandro Botticelli "`desert his painting`"
and forcing Pico della Mirandolla to abandon writing.
Savonarola wrote works such as
__Infelix Ego__,
__On the Ruin of the Church__,
and __On the Downfall of the World__ (note a common theme).
Savonarola claimed that an infinite God created an infinite cosmos with infinite worlds.
At one point, he was asked to walk through fire to prove himself,
but a rainstorm canceled the event, causing a riot.
Eventually, Pope Alexander VI excommunicated Savonarola.
He was consequently burned at the stake,
having confessed to heresy while being tortured with Domenico de Pescia and Fra Silvestro.

==== Rome: Vatican Popes and the Borgias

In 1417, the papacy was able to return to Rome, but it mostly stayed a ruined city.
By 1447, though, Pope Nicholas V was able to make it a better place.
Pope Pius II was a humanist scholar, and the papacy would become controlled by powerful families,
such as the Medici and the Borgias.
Pope Sixtus IV ordered the construction of the Sistine Chapel.
The Papal States became more centralized, and the popes became warriors.

**Pope Alexander VI** was pope for the last decade of the 15th century.
His uncle was Alfonso Borgia, **Pope Callixtus III**,
who had allegedly tried to excommunicate Halley's comet.
He was originally named Rodrigo Borgia, and he had a few children.
The important ones were **Lucrezia Borgia** and **Cesare Borgia**.
Claims of incest surrounded the family.
Cesare, who conquered Forli, was praised in Machiavelli's __The Prince__,
being used as an example of a great and harsh ruler.

=== Tudor England

==== Henry VII

Recall that **Henry VII Tudor** had won at Bosworth Field
and had become the first Tudor king of England.
The Tudors would rule England for the entirety of the 16th century.
It's perhaps interesting to note that the actual Tudor monarchs
didn't particularly like being called "`Tudor`",
because the family had been largely unimpressive before Henry VII came to power.

Henry married Elizabeth of York and unified the warring houses of Lancaster and York,
as symbolized by the Tudor symbol, a white and red rose.
He planned to make a gold plated statue of himself and put it on the tomb of Edward the Confessor.
He also made the **Court of the Star Chamber** to try to limit the power of barons.
A plot against him by John de la Pole (Richard III's nephew) involved a boy named Lambert Simnel,
who posed as Edward, Earl of Warwick,
and led some mercenaries into England, being defeated at the Battle of Stoke Field.
Another threat came from Perkin Warbeck, who pretended to be Edward IV's son.
Henry married his son Arthur to **Catherine of Aragon**, daughter of Ferdinand and Isabella,
but Arthur quickly died, leaving his brother Henry as the new heir.

==== Henry VIII

When Henry VII died in 1509, his son became **Henry VIII**,
and the position of the Tudors was secured.
He married Catherine of Aragon, and the only child of theirs that survived was Mary.
Henry started an incursion into France, but the only notable battle was the Battle of the Spurs,
where the king didn't even show up, so the war wasn't particularly effective.

At this point,
James IV of Scotland activated the **Auld Alliance** with France and declared war.
In 1513, the English met 10,000 Scots at the **Battle of Flodden Field**
(the battle actually took place at Milfield and Braxton Hill).
The English were victorious and James IV was defeated,
as chronicled by Walter Scott in his __Marmion__.
Henry also negotiated with Francis I of France at the **Field of the Cloth of Gold**,
where the two monarchs notably wrestled each other.

When Catherine wasn't able to have any more children than Mary, Henry got nervous.
The last time a female monarch was on the throne was back when Matilda was queen,
and you probably remember that hadn't worked out so well.
He decided to divorce Catherine, but **Pope Clement VII** wouldn't let him.
Henry got mad at the pope and decided to make his own church (starting the English Reformation).

The new **Church of England** wasn't much of a change from Catholicism,
except with Henry at the head of it.
In 1530, he declared his marriage to Catherine invalid, so Mary was declared illegitimate.
Henry then married **Anne Boleyn** in 1533, and Anne had a daughter named Elizabeth.
Henry got annoyed again when the queen failed to have a son,
so he beheaded her married **Jane Seymour**.
Jane gave birth to Edward, and Henry was finally happy.
Of course, Jane promptly died of sepsis, and Henry ended up quite upset.
Henry then married the German **Anne of Cleves** for the political advantages.
He didn't like her very much, so he divorced her as fast as he could.
He then married **Catherine Howard**, but since she wasn't faithful,
she ended up on the chopping block as well.
Henry's last marriage was to **Catherine Parr**,
and his health started declining, so she outlived him.
For those of you counting at home, that's six marriages total.

Henry did do things other than get married.
His 1530s **Dissolution of the Monasteries** resulted in
Robert Aske leading a revolt known as the **Pilgrimage of Grace**.
His advisors included Cardinal Thomas Wolsey and **Thomas Cromwell**.
Henry appointed **Thomas Cranmer** Archbishop of Canterbury,
where he would serve into the reign of Mary I.
Cranmer wrote the **Book of Common Prayer**, a big part of the English Reformation.
He got into an argument with **Thomas More**, Lord Chancellor,
who opposed Henry's creation of the new church.
True to form, Henry had him convicted of treason and beheaded,
so Pope Pius XI canonized More as a martyr.

Henry also launched the **War of the Rough Wooing** (1543{n-}1550),
also called the Eight Years' War,
in which he tried to enforce the Treaty of Greenwich
and force a marriage between his son Edward VI and the baby Mary, Queen of Scots.
During the War of the Rough Wooing, Edward Seymour led an expedition to burn down Edinburgh,
and the Battle of Pinkie Cleugh was so bad for the Scots that they now call it Black Saturday.

Henry died in 1547 as his paranoia and insanity got even worse.
He was buried next to Jane Seymour and was succeeded by their son, Edward.

==== Edward and Mary

**Edward VI** was only nine when he took his father's crown in 1547.
He had to stop Kett's Rebellion in Norfolk and the Prayer Book Rebellion.
At this point, England became a predominantly Protestant nation.
Edward died in 1553 at age 15 from tuberculosis, failing to live up to expectations of greatness.
John Dudley, Lord President Northumberland, put **Lady Jane Grey** on the throne.
But her reign was disputed,
so her head ended up slightly further from her neck than she would have preferred.

Thus, **Mary I**, daughter of Catherine of Aragon, took the throne.
Excluding the only partially accepted reigns of Matilda and Jane Grey,
Mary was the first true queen of England.
She was Catholic and she wanted England to be more like before the English Reformation,
so Mary burned almost 300 Protestants (recorded in John Foxe's Book of Martyrs),
resulting in her being called "`Bloody Mary`".
She imprisoned Thomas Cranmer, forced him to recant Protestantism, and burned him anyway.
Notably, she married Philip II of Spain, son of Charles V, Holy Roman Emperor (more on him later).
When Mary died in 1558, English people rejoiced.

==== Elizabeth I

**Elizabeth I**, daughter of Anne Boleyn, became queen in 1558.
She moved to reestablish the Church of England
and managed to end the conflict between Puritans and Catholics.
Elizabeth never married and was referred to as the "`Virgin Queen`",
putting her succession in doubt.
Her spymaster **Francis Walsingham**
stopped the Throckmorton and Babington plots which tried to kill her.
She also expelled the Hanseatic League from their London Steelyard, and sent raiders to burn Cádiz.

Elizabeth was able to maintain a fair amount of stability in the kingdom.
She did have to stop the Revolt of the Northern Earls in 1569,
but she managed to consolidate power fairly well.
Population grew rapidly under Elizabeth while government expanded.
Her policy was "`Video et taceo`" ("`I see and I am quiet`")
and she advocated some religious tolerance,
such as issuing the 39 Articles to concretely define a doctrine of English religion.
However, she was excommunicated by Pope Pius V by the bull __Regnans in Excelsis__.

**Mary, Queen of Scots** (Mary Stuart)
was a Queen of Scotland while Elizabeth was queen in England.
She was forced to abdicate by James after she was imprisoned in Loch Leven Castle.
Mary was Elizabeth's cousin, and she asked for Elizabeth's protection after her abdication.
Mary had claimed the throne of England as her own right,
and the participants of the Rising of the North believed that Mary was the true monarch.
Elizabeth kept her imprisoned because she thought Mary was a threat,
and she had Mary killed in 1567 for conspiring against her.

Elizabeth supported the "`Sea Dogs`", her privateers,
who included Walter Raleigh and **Sir Francis Drake**.
Drake is notable for completing the second circumnavigation of the globe.
On his way through California, he claimed land there as "`New Albion`".
He died of dysentery after losing at the Battle of San Juan.

In 1601, Elizabeth delivered the "`Golden Speech`" to Parliament,
saying that this would be her last Parliament.
Elizabeth died in 1603, marking the end of the House of Tudor that had reigned for the 16th century.

=== Reformation

==== Background

The Great **Papal Schism** was a split in the Catholic Church, occurring between 1378 and 1418.
When Pope Gregory XI ended the Avignon Papacy and returned to Rome, some people became unhappy.
When Gregory died, Romans wanted a Roman pope, so they presented **Urban VI** as pope.
But, a bunch of cardinals picked **Clement VII** and made a new papacy in Avignon.

Eventually the Antipope John XXIII gathered the **Council of Constance** (1414{n-}1418).
Gregory XII, the Roman pope, agreed, and the parties met.
A previous council at Pisa had started some Catholic reforms, and Constance continued them.
The council succeeded in ending the Schism by electing Martin V as the new pope.

Also of note at the Council of Constance was the condemnation of **Jan Hus**.
Hus, the author of __De Ecclesia__, is considered the first church reformer,
The Council of Constance ended up convicting Hus of heresy,
because he'd denounced indulgences under Antipope John XXIII.
A secular court burned him at the stake despite King Sigismund's promise of safe passage.

Hus had worked with **John Wycliffe**, another reformer around that time.
Wycliffe's supporters, the **Lollards**, opposed the Catholics in England.
The Lollards were fought by Thomas Arundel, Archbishop of Canterbury.
They also had posted their "`Twelve Conclusions`" on the doors of St. Paul's.

The Council of Constance also ruled on the Polish-Lithuanian-Teutonic wars.
They established the Diocese of Samogitia, and Pope Martin V appointed a new Polish king.

==== New Religious Ideas

Around 1517, **Martin Luther** started to talk about how the **indulgences**
that were being sold by Johann Tetzel weren't exactly legitimate,
and just a way for the pope to make money.
In defiance, Luther nailed his **95 Theses** to the door of a church in Wittenberg.
They criticized the Church and tore down the authority of the pope.

While Luther was making Theses, **Ulrich Zwingli** began a movement in Switzerland.
Zwingli would later debate Luther on various Protestant matters.
Some of Zwingli's followers thought that Luther's Reformation was too conservative,
and they became the Anabaptists.

In the papal bull __Exsurge Domine__, **Pope Leo X** excommunicated Luther.
The bull cited 41 sentences that Luther was commanded to recant,
but Luther didn't listen, sent the Pope a copy of his book __On the Freedom of a Christian__,
and burned the bull publicly in Wittenberg.
At the **Diet of Worms**, Luther was ordered to appear before a general assembly.
Holy Roman Emperor Charles V presided.
Other people at Worms included Jerome Schurff and Johann von Eck (a prominent theologian).
Luther was ordered to recant.
Obviously he didn't, saying things like
"`Here I stand, I can do no other`" (apocryphally) and
"`My conscience is captive to the Word of God`",
opting for a speech talking about how he was right.
The Diet declared Luther an outlaw and said anyone in Germany could kill him without consequence.

Luther ran away and was given shelter by Frederick the Wise in Wartburg Castle.
In 1529, the Marburg Colloquy was called together,
and Luther advocated for the idea of a Real Christ (the Eucharist isn't symbolic)
in a debate against Zwingli.

==== Counter-Reformation

The Catholics, in the wake of the Reformation, aimed to reform their own Church.
Between 1545 and 1563, a **Council of Trent** was called
It's one of the Catholic Church's most important councils,
because it embodies the ideas of this **Counter-Reformation**.
The council lasted for 25 sessions, under three popes: Paul III, Julius III, and Pius IV.

The council produced an Index of Banned Books,
while declaring that the Vulgate was the only valid Bible.
It upheld the seven sacraments as valid,
and standardized a definition of transubstantiation.
The papal bull Benedictus Deus upheld the outcome,
and the council standardized the procedure of mass (Tridentine Mass).
It had to move to Bologna temporarily due to people dying of plague.

=== Habsburg Empires

At this point,
we've mentioned a bit of what was happening in Germany when the Reformation was taking place.
Let's talk about the Habsburgs and their various leaders and lands.

==== Holy Roman Empire

In 1440, **Frederick III** was crowned Holy Roman Emperor by Pope Nicholas V.
Nicholas hoped that an alliance could help end the **conciliary movement**
undermining the Church during the Great Schism.
Frederick III married Eleanor of Portugal, and he built up lands and power.
His son became **Maximilian I**.

Maximilian's son, **Philip the Handsome**,
married **Joanna the Mad**, daughter of Ferdinand and Isabella,
heir to Castile, Aragon, and a bunch of the rest of Spain too.
She apparently deserved the epithet,
because she probably had to be forcibly removed from the corpse of her husband when he died,
and she didn't let any women approach his coffin.
Joanna had six children, and the eldest became Charles V.

By the time **Charles V** came to the throne in 1500,
the Habsburgs had gotten themselves a whole lot of power,
but the 1.5 million square miles of family domains resulted in a pretty bad overextension modifier
for the empires.
His personal union with the Spanish Empire resulted in the largest European monarchy since
Charlemagne had been in power 700 years prior.

Charles was a big opponent of the Reformation,
resulting in constant conflict with German nobility who quite liked Luther's ideas.
As Protestantism proliferated his demesne,
he reluctantly signed the 1555 **Peace of Augsburg** with the **Schmalkaldic League**.
The League was an alliance of princes that helped Martin Luther,
and the Peace of Augsburg stopped the religious struggles
by formalizing the division of Germany along denominational lines.

During the Italian Wars (fought against France), he defeated Francis I at the Battle of Pavia.
The wars, waged on and off between 1494 and 1559,
featured loads of shifting alliances, multiple turnovers of cities like Milan,
and general instability.
The 1559 Treaty of Cateau-Cambresis resulted in Spanish control of Milan
and the House of Savoy taking control of Turin.
The wars were a notable instigating factor for the Counter-Reformation and the Council of Trent.

His advisors included Guillermo del Croy, Mercurino Gattinara, and Bartolomeo de las Casas,
who helped him improve the social structure, e.g. by limiting slavery.
Juan de Padilla tried to rebel in the Revolt of the Comuneros, which Charles put down.
Other notable rebellions included one by the Arumer Zwarte Hoop (a peasant/mercenary army) in Frisia,
and the Revolt of Ghent of 1539.

Of course, Charles's control of Spain led to his signing off on the various __conquistador__
adventures in the Americas;
he enabled the destruction of the Inca and the Aztecs.

Charles abdicated in 1556, giving his brother Ferdinand I the lands of Austria and Bohemia
(beginning what would become Austria-Hungary).

==== Spain

The Spanish lands went to Charles's son **Philip II**.
Philip married Mary I of England, and the phrase "`the empire on which the sun never sets`"
was used to describe Habsburg lands at this time.
He built himself a big palace called **__El Escorial**__.
Spain went bankrupt many, many times while he was king.
One time,
his forces went into a "`Spanish Fury`" and massacred over 7,000 civilians in the Sack of Antwerp.

**The Duke of Alba** worked for Philip;
he notably established the "`Council of Troubles`" (the "`Court of Blood`")
in order to prosecute heretics.
This occurred in the Netherlands,
where **William I, the Silent, of Orange** was revolting against Philip.
William was eventually assassinated in 1584 when Spain declared him an outlaw.
The Dutch War of Independence (Eighty Years' War) lasted from 1568 to 1648,
during which Philip's army fought in the Battle of the Downs.

Philip led Spain into the later parts of the Italian Wars.
He won a Battle of the Gravelines against the French on land in 1558.
The Treaty of Cateau-Cambresis secured some territory for Spain in 1559.
The treaty ended the long-lasting Franco-Spanish wars of the era in Italy.

Philip liked to fight against heresy, and he defended Catholicism fiercely.
After the Revolt of the Netherlands, he fought Protestantism in the Netherlands.
This campaign ended up spiraling into the Cologne War.

In 1571,
Philip put his brother John (Don Juan) of Austria in command of the fleet of the Holy League.
The objective of the Holy League
was to break the Ottoman Turks' control in the eastern Mediterranean.
The League met the Ottomans at the **Battle of Lepanto**, near the Gulf of Patras.
At Lepanto, Miguel de Cervantes (author of __Don Quixote__) had to have his arm amputated.
Among the commanders of the Holy League were Augustino Barbarigo and **Andrea Doria**.
Uluch Ali, an Ottoman commander, captured the flag of the Maltese Knights during the battle.
The leading Ottoman commander Ali Pasha was beheaded, and his head was stuck on a pike.
The Holy League won a decisive victory at Lepanto.

In 1588, Philip sent his **Spanish Armada**, a fleet of 130 ships led by Pedro de Valdes,
to try and invade England.
At a second Battle of the Gravelines, this time on the sea,
the Armada lost to the smaller, faster English ships, under the command of Francis Drake,
where Drake commanded the __Revenge__.
Drake had also raided Cadiz earlier while commanding the __Elizabeth Bonaventure__,
aiming to "`singe the beard`" of the enemy king.

=== French Wars of Religion

The latter half of the 16th century was a tumultuous time for France,
and a lot of blood was shed in the wake of the Reformation.
King Henry II died in a jousting tournament in 1559.
His three sons succeeded to the throne, but they were either children or pathetic rulers.
Henry's widow **Catherine de' Medici** came to power.
In the beginnings of the wars of religion, she was an important person.
At this time, the Protestants in France were called **Huguenots**.

==== Huguenot Animosity

In 1572, Catholic princess Margaret of Valois married
Protestant prince Henry of Navarre in the "`secret nuptials`", and Catherine wasn't very happy.
She had the Duke of Guise kill **Gaspard de Coligny**, a Huguenot leader,
in an assassination signaled by ringing church bells.
Thus began the five day long **St. Bartholomew's Day Massacre**.
Thousands of Huguenots were killed,
but Henry of Navarre managed to escape by temporarily converting to Catholicism.
Catherine said that the Huguenots were plotting against her son, **King Charles IX**.
After the massacre, Pope Gregory XIII sent the king a Golden Rose, and praised the actions taken.

There were numerous smaller wars of religion in France,
but the eighth and last conflict was probably the most important.
The war was called the **War of the Three Henrys**.
The first Henry was king **Henry III of Poland**.
The second was **Henry I, Duke of Guise**, head of the Catholic League,
supported by Philip II of Spain.
The third was **Henry III of Navarre**, who had converted to Catholicism,
but now converted back to lead the Huguenots.
Guise and Henry III were both killed, and in 1589 Navarre was the only one left standing.
Navarre famously said "`Paris is well worth a mass`"
and renounced Protestantism in order to gain popularity.

==== Henry IV and the House of Bourbon

Navarre became **Henry IV of France**, first of the house of Bourbon to sit on the throne.
He instituted a policy called the __paulette__,
in which offices could be bought and made hereditary.
Henry conducted a "`Conquest of the Kingdom`"
in which his armies swept through France and took Paris
by way of the Battle of Ivry.

Henry also made social improvements.
In 1598, he issued the **Edict of Nantes** at the encouraging of the Duke of Sully.
The edict gave religious toleration and 150 places of refuge to Huguenots,
and it was opposed by Pope Clement VII.
Shortly after that, the Peace of Vervins ended the religious wars.
Henry also built the Louvre.

Even though he was generally a very popular person, Henry faced multiple assassination attempts,
such as by Pierre Barriere in 1593 and by Jean Chatel in 1594.
In 1610, Francois Ravillac, a Catholic fanatic,
stabbed Henry to death in in his coach on the Rue de la Ferronnerie.

=== Age of Discovery

Starting in the 15th century, Europeans started going all over the globe.
They discovered new places, new routes,
and opened up new trade of plants, animals, food, disease, violence, and corruption.

==== Atlantic Ocean

In Portugal, **Prince Henry the Navigator** wanted to know more about places like Africa.
He wanted to find Prester John,
a legendary man that was supposed to have lots of rich lands in Ethiopia.
He sponsored Joao Goncalves Zarco, who found the Azores and Madeira.
The Portuguese used the caravel, a smaller ship that was able to sail windward very effectively.
Henry died in 1460, and Portuguese explorers found the "`Gold Coast`" in modern-day Ghana.
Portugal would colonize both sides of Africa, but not the land in between.

Next door to Portugal,
Castile in Spain had taken rule of the Canary Islands off the coast of Africa.
**Ferdinand and Isabella**, the Catholic Monarchs, had completed the __reconquista__
late in the 15th century, driven the Moors out of Spain, and wanted to find new trade routes.
When they conquered Granada in 1492, the rulers funded **Christopher Columbus** of Genoa
and his expedition to bypass west Africa and the Portuguese-controlled routes.

Columbus set sail from Palos de la Frontera on the ships Santa Maria, Nina, and Pinta.
He first sailed to the Canary islands, and then went west across the Sargasso Sea.
After five weeks, he landed in the Bahamas (which he called San Salvador),
and he thought he was in the West Indies.
He founded the settlement of __La Navidad__ in modern-day Haiti,
kidnapped some natives, and brought them back to Spain with him.

After Columbus came back,
the Spanish and Portuguese decided that they needed to stay out of each others' way.
Pope Alexander VI sent a bull to Ferdinand and Isabella dividing the lands.
King John II of Portugal wasn't happy with this, because it didn't let him get to India.
In 1494, after negotiations between the Iberian countries,
they signed the **Treaty of Tordesillas**.
Portugal got the islands discovered on Columbus's first voyage,
and Africa, Asia, and modern-day Brazil.
Spain got basically everything else, mostly uncharted territory.

In 1497, Henry VII of England commissioned **John Cabot** to explore the New World.
He sailed from Bristol and landed somewhere around Newfoundland,
and explored trying to find new routes.
He was the first non-Viking European to explore North America.
At the same time, Joao Fernandes Lavrador was sent by Portugal, and he found Labrador.

Columbus would discover the mouth of the Orinoco in northern South America.
**Amerigo Vespucci** reached Guyana in 1499, and he sailed southward.
Vespucci found the mouth of the Amazon River, and turned around.
His first name would of course be notable in naming the Americas,
because it was Vespucci that suggested that the lands were not the Indies,
but actually a New World.

In 1500, the second Portuguese India Armada, commanded by **Pedro Cabral**.
They landed on the Brazilian coast,
and they called it __Ilha de Vera Cruz__ because they thought it was an island.
Cabral's expedition connected Europe, Africa, America, and Asia.

In the early 1600s,
**Henry Hudson** was an English explorer who tried to find the Northwest Passage to China.
When he wanted to keep going west, though, his crew mutinied.

==== Indian Ocean

Portugal had rejected Columbus's ideas of going west to get to India twice already,
because it was just too far.
John II sent **Bartolomeu Dias** in 1487 to go around Africa,
but Dias wasn't exactly successful, and he returned from the Cape of Good Hope.

In 1497, Manuel I, the new king, sent a fleet under **Vasco da Gama** to explore.
They passed the Great Fish River where Dias had turned back and just kept going.
He ordered the __Sao Rafael__ burned near Malindi, Kenya.
They made it to India in 1498.
Da Gama was named viceroy in India in 1524.
The Lusiads were written in honor of da Gama.

Cabral's fleet that had landed in Brazil came back around Africa
and reached Madagascar, Mauritius, and more.

Some other explorers also made it to southern China and traded there,
as well as the "`Spice Islands`" in the Indian Ocean.

==== Pacific Ocean

In 1513, the Spanish explorer **Vasco Nunez de Balboa**,
hearing of another sea, trekked across Panama.
His crew fought battles, bushwhacked through dense jungle, and climbed mountains.
Balboa became the first European to see the Pacific Ocean from the Americas.
They found a bay that they called San Miguel, and he called the ocean the "`South Sea`".

In 1516, **Ferdinand Magellan** presented a plan
to sail all the way around the world to Charles I, king of Spain.
Magellan had previously served under Alfonso de Albuquerque during the conquest of Malacca.
In 1519, five ships including the flagship __Trinidad__ left from Seville.
Three of the ships were the first to reach Tierra del Fuego at the southern tip of the Americas.
They went through the straits that we now call the Straits of Magellan.
At this point, the Pacific Ocean was given its name because it looked so still.
Magellan was killed by a spear
at the **Battle of Mactan** against Philippine natives led by Lapu-Lapu.
The Spaniard Juan Sebastian del Cano (Elcano) commanded the return to Spain in 1522,
completing the first circumnavigation of the globe.

==== Conquistadors

While the Portuguese were exploring the Indian Ocean and trading a lot,
the Spanish wanted to look for gold in the New World.
The people that went on these expeditions were the **conquistadors**,
and they were mostly in it for gold.

===== Cortes and the Aztecs

In Mexico, the **Aztec Empire** had been prospering and generally minding their own business.
Their capital was modern-day Mexico City, known in that time as **Tenochtitlan**.

A conquistador looking to get to the center of Mexico,
**Hernan Cortes**, heard that the Aztecs had lots of gold.
Cortes took Veracruz and asked to meet with the Aztec Emperor **Moctezuma II**.
When Cortes got to Tenochtitlan,
Moctezuma let him and his men in and gave them lots of gold in order to better get to know them.
The Aztecs thought that Cortes was their feathered snake god Quetzalcoatl.

When the Aztecs attacked the Spaniards on the coast, Cortes took the emperor hostage.
The governor of Cuba, Diego Velazquez,
sent forces in 1520 led by Panfilo de Narvaez to stop Cortes.
Cortes left a couple hundred men in Tenochtitlan and stopped the group.
When his men killed a bunch of people in Tenochtitlan,
he tried to get back, but Moctezuma was already dead.
Many of Cortes's men died
when his settlement was attacked on __La Noche Triste__ (The Night of Sorrows),
and Cortes had to flee.
He returned, besieged Tenochtitlan, and took the city from the new ruler Cuauhtemoc,
claiming the new Mexico City for Spain.

===== Pizarro and the Incas

Further south, on the west coast of South America, the **Inca Empire** was flourishing.
These were the Andean people who had built Macchu Picchu
(excavated by Hiram Bingham many years later),
and had grown under their king **Pachacuti** many years ago.
Their math systems involved knotted strings called __quipus__,
and their capital was at Cuzco, a city shaped like a mountain lion,
from which they ruled the four __suyus__ that made up the empire.
In the early 16th century, their king was **Atahualpa**, son of Huayna Capac,
who had gotten power by killing his brother Huascar in a civil war at the Battle of Quipaipan.

**Francisco Pizarro** had been with Balboa when they had crossed Panama,
and he had served a short time as the mayor in Panama City.
These days, Pizarro had his own men, and they explored the south looking for gold
(because that's what explorers do).
He worked with Hernando de Luque and Diego de Almagro to divide the profits.
In 1524, they tried to conquer Peru and utterly failed.
When they landed again, they found some gold,
so Pizarro stayed on land while the others went back for reinforcements.

When reinforcements were rejected by the governor of Panama, they returned.
At the Isla de Gallo, Pizarro drew a line in the sand,
saying that whoever wanted to come with him towards the riches of Peru could,
and the choice was theirs and theirs alone.
Thirteen men decided to stay with Pizarro (they were known as the "`Famous Thirteen`").
By 1528, they discovered more riches in the Tumbes region of Peru.

Pizarro headed back to Spain and asked King Charles I to help with another expedition to Peru.
In 1530, he departed and found that Tumbes was destroyed;
Pizarro used the place to found San Miguel de Piura, a new settlement.
He took his men and went to meet Atahualpa, who turned the Spaniards away.
At the **Battle of Cajamarca**,
200 Spanish soldiers attacked and defeated an Inca army of 80,000 men.
Pizarro made Atahualpa fill a "`ransom room`" with gold and two rooms with silver,
but then decided to convict him of conspiracy and kill him anyway.
Pizarro proceeded to take Cuzco and found the city of Lima in Peru.

===== North America

Some other important explorers explored the northern parts of America.

In 1512, Ferdinand of Spain asked **Juan Ponce de Leon**,
the governor of Puerto Rico, to explore the Americas.
Leon had to finance his own expeditions, but he could govern whatever he found.
He left from Puerto Rico in 1513 and he found Florida, thinking it was an island.
He also discovered the Gulf Stream in his travels.
Now, however, he's probably most associated with his supposed obsession
with finding the Fountain of Youth in or around Florida.

In 1539, **Francisco Coronado** launched an expedition into the American southwest.
He was the first European to visit the Grand Canyon,
and he searched for Cibola and the Seven Cities of Gold.

In 1541, **Hernando de Soto**, who had been exploring Florida, decided to move west.
His troops were the first to see the Mississippi River, and they moved up to the Arkansas River.
