== Revolutions in Europe

[quote.epigraph, Voltaire]

  History is filled with the sound of silken slippers going downstairs and wooden shoes coming up.


The turn of the 19th century was full of revolutions in Europe.
France's monarchy got all turned upside-down, Napoleon took power, and rebellions swept the continent.

=== French Revolution

The French Revolution was a particularly important event for Europe,
and it was influenced partly by the American Revolution.

==== Louis XVI

**Louis XVI**, the grandson of Louis XV,
came to power in 1774, when his father, the Dauphin, died.
His wife was **Marie Antoinette** of Austria.
Louis supported the American Revolution starting in 1776 until independence.
In the beginning of his reign, he wanted to make France more Enlightened,
so he tried to abolish serfdom, stop the __taille__, and increase religious tolerance.
His foreign minister Charles Gravier
was an important part in Louis's support of the American Revolutionaries.

==== Background

Louis's financial reforms were carried out by **Turgot** and Malesherbes,
but the nobles weren't happy with that.
Turgot had been appointed by Louis's adviser Maurepas,
so Louis fired Turgot and replaced him with finance minister **Jacques Necker**.

Necker was given the title of Director-General of France
(he couldn't be named controller because he was Protestant),
and quickly became popular through various tax reforms.
Necker tried to divide the __taille__ tax more fairly,
and he took many loans to help finance the American Revolution,
a venture which the French were increasingly in favor of.
Necker published the __Compte rendu__,
in which he summarized government cash flow in order to provide transparency
into the monetary inner workings of the government

By 1781, public opinion had turned on the high cost of the war,
and Necker was left high and dry with no friends in the court as a result of his reforms.
As a result of increasing public and internal pressure (including from the king and queen),
Necker resigned.

Louis wasn't happy with Necker and would replace him with Charles Alexandre du Calonne.
When Calonne wasn't able to get France out of debt, Louis called the Assembly of Notables.

==== Tennis Court Oath

The king was losing power, and people were calling for him to convene the **Estates General**,
an assembly of the nobility, clergy, and common folk
which hadn't been called since 1614 under Louis XIII.
In 1788, Louis succumbed to public pressure the Estates General.

The Third Estate wasn't pleased by the fact
that they weren't as well off as the nobility and clergy.
They split off in June 1789 and declared themselves the **National Assembly**.
When the Menus Plaisirs at Versailles was locked
and the 577 assembly members were left without a place to meet,
they went to an indoor tennis court and took the **Tennis Court Oath**.
The agreement, written by Jean-Sylvan Bailly and Jean-Joseph Mounier,
promised that they would stay together until a new constitution was created.
Other notables at the Tennis Court Oath were Abbe Sieyes and Mirabeau.
Jacques-Louis David made a sketch of the Oath.

==== Outbreak of Revolution

On July 11, 1789, Jacques Necker was dismissed.
People were mad, since Necker had been doing good things for the general populace.
On July 14, some insurgents decided to storm the **Bastille**.
The fortress prison had become a symbol of the power of the king,
despite only holding seven prisoners at the time.
The insurgents went for ammo caches inside the building.
The commander of the Bastille, Bernard de Launay, was killed and his head was put on a pike.
After the storming, Jean-Sylvan Bailly became mayor following the death of Jacques de Flesselles.
The wave of revolution resulted in the Great Fear.

In August, the **Declaration of the Rights of Man** was passed.
It was heavily influenced by the Declaration of Independence in the USA,
where the **Marquis de Lafayette** had worked with Jefferson.
The National Constituent Assembly then worked to make a new constitution.

In October, there was a **Women's March** on Versailles,
protesting the high price of bread by means of weapons.
The mob stormed the palace, killing some guards.
Louis gave in to their demands and moved his family
from Versailles to the **Tuileries** in Paris.

==== Constitutional Monarchy

Around this time, the **Jacobin** Club (Society of Friends of the Constitution) was forming.
The Jacobins would become a more radical group of revolutionaries,
in contrast to the **Girondists**.
Jacobin members included **Maximilien Robespierre** and **Georges Danton**,
who would become quite important in the coming years.
Robespierre wrote the "`Defender of the Constitution`" to oppose war with Austria.

At the meetings that tried to define a new constitution,
issues were raised regarding how the new government would govern.
It was decided to continue the monarchy checked by a constitution.
Louis would remain in power, with some weaker power.
These new ideas weren't very popular with the radicals.

==== Terror and War

In 1791, Louis XVI wasn't very happy with the state of the revolution,
so he decided to take his family and run for the border.
They fled towards **Varennes**, trying to get to Austria and safety.
Louis posed as the butler of a fake Russian baroness played by the dauphin's governess.
But, they were captured and placed under house arrest in the Tuileries.

In the **Brunswick Manifesto**, Austria and Prussia demanded that Louis be put back in power.
Not being fans of the idea, the Legislative Assembly went to war with Austria and Prussia.

Because they thought that he was conspiring with enemies of France,
the people condemned Louis to death.
He was executed by **guillotine** on the Place de la Concorde in January 1793,
stripped of his title.
His final words were drowned out by a National Guard drum roll ordered by Antoine-Joseph Santerre.
Marie Antoinette would be killed in the same way nine months later.

[sidebar]
Let's talk about the guillotine.
It wasn't the first beheading machine in Europe;
the Halifax Gibbet and the Scottish Maiden had been used in the past.
After Louis XVI banned the breaking wheel in France,
a committee including Joseph-Ignace Guillotinn and Antoine Louis
was formed to create a new execution device.
The prototype for the guillotine was then created by Antoine Louis, working with Tobias Schmidt.

Lots of violence broke out at this point.
The wars weren't going very well, and **sans-culottes** (literally: without culottes),
poor workers and some radicals, were rioting.

This was the point that the **Committee of Public Safety**
rose to power under the leadership of the Jacobins.
Robespierre was the leader of the Committee,
and he ordered executions in large numbers during the ensuing **Reign of Terror**.
At least sixteen thousand people lost their lives to the guillotine.
Many Girondins were arrested, including Jacques Pierre Brissot.

**Jean-Paul Marat** was a journalist who was known for his inflammatory rhetoric.
Marat had been a scientist and doctor, but he became the editor of __Friend of the People__.
He wrote __The Chains of Slavery__ and __A Philosophical Essay on Man__.
Marat spent a lot of time attacking Girondins, and when he was in his bath,
**Charlotte Corday**, a Girondin assassin, assassinated him.
His death was painted by Jacques-Louis David.

The **Vendee Revolt** was a 1792 uprising against the government.
The rebels were people who were loyal to the church and to the king.
This counter-rebellion was suppressed by General Lazare Hoche at battles such as Savenay and Cholet.

Members of the Committee of Public Safety such as Georges Danton were being removed all the time.
Robespierre, "`the Incorruptible`", became more and more powerful, and more and more radical.
A new Constitution of 1793 was adopted; it granted universal male suffrage.
Robespierre, in 1794, created a new religion, known as the **Cult of the Supreme Being**,
which replaced the Cult of Reason.
The French calendar was changed --- the new months were completely different.

==== The Directory

In the new month of Thermidor, people stopped loving Robespierre, who had gone off the deep end.
The moderate factions, led by Paul Barras, went and arrested Robespierre at the Hotel de Ville.
As a result of this **Thermidorian Reaction**, Robespierre was guillotined,
and a five man governing entity called the **Directory** rose to power.

The Directory was against the pointless death of the Reign of Terror,
but it wasn't effective either.
It did manage to end the Vendee Revolt, and its final leader was the Abbe Sieyes.
The Army, led by **Napoleon Bonaparte**,
took control of France after deposing them in the Coup of 18 Brumaire.
This established a Consulate, and Napoleon would declare himself Emperor in 1804.

=== Napoleonic Era

The years of Napoleon were filled with war and conquest.
It got to the point that Napoleon was basically fighting all of Europe.

==== Rise of Napoleon

Napoleon had been born on Corsica, and he served in the French army for a while.
His brother was Joseph, who would help when Napoleon became a leader.
He married **Josephine de Beauharnais** and during the French Revolutionary Wars,
he led a campaign in Italy.
He signed the **Treaty of Campo Formio** with Austria and divided Italy with them.
In 1797, he'd helped start the second phase of the directory during the coup of 18 Fructidor.

In 1798, Napoleon had led an expedition into Egypt, fighting against the Ottomans.
He defeated the Mamluks at the **Battle of the Pyramids**, securing the territory.
The campaign started the modern study of Egyptology.
Later, the British fleet destroyed the French at the **Battle of the Nile**,
and Napoleon was forced to leave Egypt later.

In the **18 Brumaire Coup** (1799),
Napoleon overthrew the Directory in alliance with officials such as Joseph Fouche and Talleyrand.
The new Consulate drafted the Constitution of the Year VIII and Napoleon was elected First Consul.
In 1800, his army crossed the Alps into Italy, where the Austrians were occupying the land.
At the **Battle of Marengo**,
Napoleon defeated the Austrians and barely avoided being pushed out of Italy.

While ruler, Napoleon faced the __Conspiration des poignards__
and the Plot of the Rue Saint-Nicaise (the "`infernal machine`").
He used these and made himself the Emperor of the new French Empire.
He was crowned by Pope Pius VII at Notre Dame.
In 1805, he was crowned King of Italy and he added 18 Marshals of the Empire to secure it for him.

==== Britain and Nelson

At this time, George III was still king of Britain.
In 1801, Great Britain and Ireland joined to form the United Kingdom of Great Britain and Ireland.

**Horatio Nelson** was one of the most important commanders in British history.
He had learned from his uncle, Maurice Suckling.
Nelson had also taken a trip to the Arctic when he was a kid,
so there's a famous painting of him hitting a polar bear with a rifle.
He was a lover of Emma Hamilton, for whom he killed Admiral Caraciollo of the Pathenopean Republic.

Nelson served under Samuel Hood, and at the Siege of Calvi, he was wounded and he lost his eye.
Due to his service under Sir John Jervis at the Battle of Cape St. Vincent,
he was knighted by the king.
Nelson also led British forces at the Battle of the Nile during Napoleon's ventures into Egypt.
At Santa Cruz de Tenerife, he lost his arm while leading an assault.

==== Wars with Napoleon

In 1802,
France and Britain had agreed to end hostilities resulting from the War of the Second Coalition
with the **Treaty of Amiens**.
The **War of the Third Coalition** (1805) was the end of that peace.

Napoleon seriously considered invading Britain, but he needed a stronger navy.
When he got one, he met the British fleet under Nelson at the **Battle of Trafalgar**.
Nelson commanded HMS __Victory__.
Nelson copied his old admiral Jarvis by trying to split Napoleon's forces
and taking the French in two blocks.
At the start of the battle, he famously sent the message
"`England expects every man to do his duty`" by flag signals to the other ships.
John Pasco, who was sending the signal, had the word "`confides`" replaced with "`expects`".
Nelson's fleet was hit by cannon fire,
but the British were able to break the center, split the French,
and take the __Redoubtable__ and the __Bucentaure__.
Cuthbert Collingwood commanded the __Royal Sovereign__ and attacked the French from the rear.
During the battle, the Admiral Villaneuve was captured and Britain lost no ships,
but Nelson was shot by a sniper while on deck and killed.
Trafalgar ensured that Napoleon stopped trying to take Britain.

After his navy was crushed at Trafalgar,
Napoleon faced the Austro-Russian army at the **Battle of Austerlitz** in Moravia.
Austerlitz is sometimes called the Battle of Three Emperors:
Napoleon (France), Alexander I (Russia), and Francis II (Holy Roman Empire).
Napoleon chose to split his army across the two massive opposing armies
and he fought from the low ground.
The most important charge, led by Marshal Nicolas Soult with St. Hilaire and Vandamme,
was a big push to take Pratzen Heights.
This led to the Austrians and Russians being split, so the French army encircled and defeated them.
Napoleon only lost one battalion in the battle; Austerlitz is perhaps his greatest victory.
The battle led to the **Treaty of Pressburg**, which created the Confederation of the Rhine.
It was a nail in the coffin of the Holy Roman Empire;
the Habsburgs had to pay indemnities of forty million francs.
The French proceeded to occupy Vienna and Venice, and Napoleon grew even more confident.

In 1807, Napoleon had signed the **Treaty of Tilsit** with Tsar Alexander I.
But, in 1812, Napoleon and Alexander disagreed on the issue of Poland.
Napoleon decided to invade Russia with 650,000 men in his __Grand Armee__.
They won some victories, such as the Battle of Smolensk.
For almost 3 months, the Russians retreated, burning the earth as they went.

The armies then met at the **Battle of Borodino** near Moscow.
Napoleon's forces, aided by Prince Eugene and Count Barclay de Tolly,
scattered Mikhail Kutuzov's soldiers.
Notable places in the battle included the Raevsky Redoubt and the "`Bagration fleches`".
Borodino was the bloodiest battle of the Russian Campaign, but it wasn't decisive.
Napoleon entered Moscow, and the Russians retreated.
When the infamous Russian winter came around,
Napoleon gave up, left his men, and went back to Paris.

Napoleon also fought against Spain, Portugal, and Britain in the **Peninsular War** (1808),
part of the **War of the Sixth Coalition**.
It featured the first use of the term "`guerrilla warfare`".
The British **Duke of Wellington** devised the Lines of Torres Vedras,
a set of strong forts and such,
in order to protect Lisbon after the Battle of Talavera.
Ande Massena tried to attack the Lines, but he failed.
In early 1812, Wellington defeated Napoleon at the **Battle of Salamanca**.
During the war, the **Treaty of Kiel** took Denmark out of the war.

At the **Battle of Leipzig** (a "`Battle of the Nations`")
during the War of the Sixth Coalition,
30,000 troops were stranded in the city after the bridge over the Elster River was demolished,
leading to Napoleon's defeat there at the hands of an Austro-Prussian force
led by Prince Schwarzenburg and General Blucher, as well as Alexander I of Russia.
Important locations of engagement include Markkleeberg and Liebertwolkwitz,
while Antoine Drouot commanded artillery on Gallows Hill.

After the War of the Sixth Coalition,
Napoleon signed the **Treaty of Fontainebleu (1814)** with Austria, Russia, and Prussia.
Napoleon was exiled to Elba, and Louis XVIII was restored to the throne in France.

==== Congress of Vienna

The **Congress of Vienna** was a Congress convened in order to figure out what to do
following the French Revolution and the Napoleonic Wars.
It lasted from September 1814 to June 1815.

The Congress was convened and chaired by **Klemens von Metternich** of Austria,
who had replaced Johann Stadion as Foreign Minister.
Metternich's deputy was Johann von Wessenberg.
Other representatives at this "`concert of Europe`" included
**Viscount Castlereagh** from Britain,
who would be succeeded by the Duke of Wellington,
and later, the Earl of Clancarty.
**Talleyrand** represented the French, and Alexander I attended for Russia.

As a result of the Congress of Vienna,
many boundaries were shifted and power was redistributed in Europe.
Norway and Sweden were united under a single ruler, and Krakow was declared a new free city.
A new German Confederation consisting of 38 states was created,
and Switzerland was officially declared neutral.
The Congress condemned slavery, but didn't outlaw it.

==== The Hundred Days

The Congress of Vienna was interrupted by the **Hundred Days**.
Napoleon returned from exile on Elba in March 1815,
sparking the War of the Seventh Coalition.

After failed attacks at Quatre-Bras and Ligny,
Napoleon met the Duke of Wellington at the **Battle of Waterloo**.
Wellington was joined during the battle by Prussians Gebhard von Blucher and H.E.K. von Zieten.
Napoleon's forces under Marshal Ney captured La Haye Saint, but Zieten was able to attack back.
Troops under D'Erlon attacked Mont-Saint-Jean and a farm.
Waterloo signaled Napoleon's final defeat.
Following the battle,
the Lion's Mound was constructed to commemorate the death of **William the Silent** of Orange.

Napoleon was subsequently exiled to Saint Helena, where he moved into Longwood House.
He died in May 1821.

=== Britain's Internal Struggles

The Napoleonic Wars had really taken their toll on England.
Famine and unemployment led to widespread poverty, and the Corn Laws weren't helping much either.
In response, the Manchester Patriotic Union put together a demonstration led by Henry Hunt, a famous radical.
After the meeting,
William Hulton dispatched units under Hugh Birley to St. Peter's Field
to arrest the people leading it.
Birley was drunk, and cavalry charged into the crowd,
resulting in 15 deaths and hundreds of injuries.
Following this **Peterloo Massacre**,
Lord Sidmouth introduced the **Six Acts**, including
the Training Prevention Act,
the Seditious Meetings Act,
and the Seizure of Arms Act.
The name was given by James Wroe in his newspaper __The Observer__.

In 1838, a new movement called the **Chartists** started.
Named after the People's Charter of 1838 that they presented to Parliament,
the working class movement aimed for political reform.
Led by William Lovett, the Chartists called for a secret ballot and universal male suffrage.
John Frost led the militant branch of the group in the Newport Rising.
Protesters removed plugs from steam boilers, disabling them, in the Plug Plot.
Their newspaper, the __Northern Star__, was edited by Feargus O'Connor.
Thomas Carlyle wrote a pamphlet, __Chartism__, about the movement.
