== World War I

[quote.epigraph, Otto von Bismarck, 1888]

  One day the great European War will come out of some damned foolish thing in the Balkans.


There were many causes of World War I.
Chief among these were militarism, imperialism, entangling alliances,
and a great spirit of nationalism.
Realize that at this point,
the royals of Europe were all related to each other in one way or another,
and that really helped create this complex web of relationships, obligations, and alliances.
Europe was a powder keg --- all that was left was to ignite it.

=== Background

==== Kaiser Wilhelm II

The last of the German Kaisers was **Wilhelm II**.
Otto von Bismarck was in power under Wilhelm until he was dismissed in 1890
and replaced by **Leo von Caprivi**.
He built a greater navy for the German empire, led by Admiral **Alfred von Tirpitz**,
containing the new German submarines, the U-Boats.
Helmut von Moltke the Younger led the General Staff of Wilhelm's army while he was in power.

When the Daily Telegraph interviewed the Kaiser,
he called the English "`mad, mad, mad as March hares`",
which didn't do much for his popularity abroad.
During the Moroccan Crisis, in which he sent the __Panther__ into **Agadir**,
Wilhelm called for the Algeciras Conference.

==== Death in Sarajevo

The **Black Hand**
was a Serbian secret military society that was formed by Serbian army leaders.
Led by Dragutin Dimitrijevic, codename "`Apis`", the Hand aimed to unite Serbia and Montenegro.

**Archduke Franz Ferdinand**, nephew of Austro-Hungarian Emperor **Franz Joseph**,
decided to marry Countess Sophie von Chotek.
In order to let this go through, he renounced any regal claims that his children held,
thus allowing for Charles I of Austria to be crowned.

In 1914, Apis decided that Franz Ferdinand should be killed.
The Archduke was visiting Sarajevo, and he was driving through town in a motorcade.
Three young Serbs named **Gavrilo Princip**, Nedeljko Cabrinovic, and Trifko Grabez
were put in position, impersonating customs officials, to blow him up, shoot him, etc.
Cabrinovic failed his grenade attack.
When Franz Ferdinand was mistakenly directed off the Appel Quay by the driver Leopold Lojka,
Princip put two bullets into the car.
The first went into the Archduke's neck, and the second hit the Duchess.

The assassination of Franz Ferdinand launched a crisis.
Austria-Hungary issued the **July Ultimatum** against the Serbs,
but they created it to be impossible to fulfill.
The empire was looking for war, and they would have it.

On July 28, Austria-Hungary declared war on Serbia.
The next day, Russia mobilized against Austria-Hungary.
Germany then declared war on Russia,
Britain on Germany,
and thus began the Great War.

=== War in Europe

Let's look at some of the important bits of military history of World War I.

==== A War on Two Fronts

The **Central Powers**, Germany and Austria-Hungary, were surrounded.
They were forced to fight a land war on two fronts; France to the west, and Russia to the east.
The Germans devised the **Schlieffen Plan**,
in which they would quickly defeat the French and then continue the war against Russia.
The plan was deployed by Helmut von Moltke the Younger,
and originally planned to march through the Netherlands.

The man in charge of French forces at the start of the war was **Joseph Joffre**,
a man who realized that this would be a different war than the ones France had fought previously,
and dismissed numerous corps commanders and divisional commanders,
replacing them with better wartime commanders such as Ferdinand Foch and Philippe Petain.
The French deployment plan against the Schlieffen Plan was Plan XVII.

==== Battle of the Frontiers

France waged the **Battle of the Frontiers** across the eastern border of France.
While the middle of the line was beaten back by German forces after attacks into Alsace-Lorraine,
field commander Charles Lanrezac was forced to hold the Germans at the left flank
with the aid of British Commander-in-Chief Sir **John French** (be careful with this name),

The Germans managed to break through the Franco-British defense,
allowing them to take Liege and Namur and force their way into northern France.
This would end up forcing the First Battle of the Marne.

On the way,
the siege at Liege was taking so long that **Erich Ludendorff** took a small force with him,
found his way to the front door of the fortress,
knocked on the door, and demanded the French surrender.
They did.

==== First Battle of the Marne

In 1914, the Schlieffen Plan was halted at the **First Battle of the Marne**.
The French Sixth Division, under Philippe Petain,
held off the Germans until 600 taxicabs commissioned by General Joseph Gallieni
brought reinforcements to the battlefield,
forcing the Germans to retreat.
Other notable commanders included Louis Francet d'Esperey,
whom Joffre had replaced Lanrezac with just prior, following the Battle of St. Quentin.

==== Race to the Sea

Historians these days seem to be cooling on the term **Race to the Sea**,
since it implies that the outflanking effort
which resulted in trenches being dug toward the Belgian coast
would somehow result in something when they reached it.
British and French forces aimed to push forward against the Germans,
while the Germans simply wanted to defend the territory they had gained.
As a result, German trenches were far better constructed and more intended for permanence.

==== Ypres

Five battles took place at **Ypres**, a city the British called "`Wipers`".

The first battle was part of the First Battle of Flanders in late 1914.
The battle started following the failure of the Race to the Sea to accomplish anything useful,
in terms of territorial gains.
Subconflicts included the Battle of Langemarck and La Bassee and Armentieres.

The Second Battle of Ypres was fought in April 1915.
It notably included the first use of mass German poison gas attacks,
in which chlorine was used in violation of the Hague Convention.
The battle included conflicts at St. Julien and Kitcheners' Wood.

The **Third Battle of Ypres** is also known as the **Battle of Passchendaele**.
During it, the ANZAC Corps took Broodseine Ridge and Polygon Wood,
and the Canada Corps under Arthur Currie took Passchendaele Ridge.
Other commanders included Douglas Haig and Robert Nivelle.

There were two other battles at Ypres.

==== Verdun

In 1916, the German Fifth Army attacked near **Verdun**, on the Meuse River,
attempting to capture a critical point to take the city.
The French commander was the defense-minded **Philippe Petain**,
who ordered that the French were not to withdraw.
Robert Nivelle said that "`They shall not pass!`",
but Petain is often credited with the quote as well.

General **Erich von Falkenhayn**, Chief of Staff of the Armed Forces of Germany,
aimed to "`bleed France white`" at Verdun, having been stopped at the Marne.
Germans went into battle with grenades, not rifles.
During the battle, La Voie Sacree,
the Sacred Way, was used to channel supplies and reinforcements.
Commanders included Emile Driant (killed), Fernand de Langle de Cary (removed),
and Charles Mangin, who captured Fort Vaux and Douaumont.
Important focuses of fighting included Mort-Homme and Cote 304.
Victory at the battle resulted in Petain being hailed as "`the Lion of Verdun`"
and promoted out of there.

==== The Somme Offensive

The **Battle of the Somme** (1916)
was meant to relieve some of the pressure placed on the Allies at Verdun.
The Allies were led by Ferdinand Foch and Douglas Haig,
and the offensive was one of the bloodiest battles of the war.
On the first day, 60,000 British troops were killed.

Right before Zero Hour, a huge mine exploded under Hawthorn Ridge Redoubt,
as part of a huge preliminary attack, beginning the battle.
Fighting locations included High Wood, during the Battle of Bazentin Ridge,
and subconflicts included the Battle of Albert.
The first tanks were placed into combat, and the British Mark I tore through barbed wire.

After the stalemate at the Somme, the German army retreated to the **Hindenburg Line**,
a network set up to provide defensive positions.
One section of the line was called the Siegfried Line.

==== Gallipoli

The **Gallipoli Campaign**, aka the Dardanelles Campaign,
took place on the Gallipoli peninsula in the Ottoman Empire.
The aim of the campaign was to open a path to Constantinople via the peninsula.
The offensive was supported by **Winston Churchill**, First Lord of the Admiralty,
and HH Asquith, the Prime Minister.

The first landing of Gallipoli is now marked by ANZAC day (Australian and New Zealand Army Corps).
ANZAC took heavy casualties during the campaign.
The Allies fought at Salonika, and were unable to get reinforcements through.
The largest battle was fought at Suvla Bay, during the August Offensive of the campaign,
where Frederick Stopford was stopped by Otto Liman von Sanders.
Following the August Offensive, Charles Monro was appointed as a replacement for Ian Hamilton.
Other notable locations included Krithia, Scimitar Hill, and Chocolate Hill.

The failure of the Gallipoli campaign
led to the resignation of Churchill as First Lord of the Admiralty,
and Asquith fell into disfavor, paving the way for the rise of David Lloyd George in Britain.

==== Jutland

The important naval battle that comes up here is the **Battle of Jutland**,
between steel Dreadnought battleships.
The battle was fought in the North Sea, near Denmark,
and it was the only full scale battleship battle in the war.
The Allied Grant Fleet was commanded by **Admiral John Jellicoe**,
and the Central High Seas Fleet was under German Vice-Admiral Reinhard Scheer.

Scheer sank the __Indefatigable__ and the __Queen Mary__ during the battle.
Scouting forces were led by David Beatty and Franz von Hipper,
and phases of the battle included a "`run to the south`" and a "`run to the north`".
During a night fighting part of the battle, there were limited radio capabilities.

==== The Hundred Days Offensive

The **Hundred Days Offensive** would ultimately cause the end of the war.
The offensive began in August 1918 with the **Battle of Amiens**,
during which Allied forces put together huge advances;
Erich Ludendorff referred to the first day of the battle as "`the black day of the German Army`".
Troops under Henry Rawlinson silenced the artilleries
and used fake radio messages to confuse the Germans.
The Hundred Days Offensive also allowed the Allies to break the Hindenburg Line.

=== American Involvement

We haven't really talked about the American role in the war yet.
First, however, we need some background.

==== Woodrow Wilson

President of Princeton University prior to running for public office,
**Woodrow Wilson** was the first Democrat since Andrew Jackson to win two consecutive terms.
Wilson had written __A History of the American People__ and he advocated a "`New Freedom`".

His election had been managed by William McCombs, and he was supported by William Jennings Bryan.
Wilson was largely elected because of the fact that Teddy Roosevelt's Bull Moose Party
split the Democratic vote with Taft's Democratic party.

While in office, Wilson would pass many important bills.
Among these were the Underwood Tariff, the Clayton Anti-Trust Act,
and the Federal Reserve Act (Glass-Owen Act).
Also notable were the creation of the Federal Trade Commission (FTC)
and the passage of the Federal Farm Loan Act.

Wilson was a big proponent of neutrality in the opening phases of the Great War.
In 1916, he won reelection over Charles Evans Hughes under the slogan "`He kept us out of war!`"

==== Joining the War

RMS **Lusitania** was a British ocean liner owned by the Cunard line.
On May 7, 1915, a German U-boat torpedoed the ship, sinking it.
The Germans thought that there were munitions on the boat,
but it was only admitted that the ship was carrying cartridges.
There were Americans on the ship,
and William Jennings Bryan resigned following the event ---
Robert Lansing took over as Secretary of State.

In 1917, German Foreign Secretary Zimmerman sent a message to Heinrich von Eckardt.
This **Zimmerman Telegram** was intercepted by British Intelligence and decoded at Room 40.
The message called for Mexico to attack the US to take back territories like New Mexico and Texas.
After the British forwarded the message to Woodrow Wilson, the American people were outraged.
The note was an important catalyst in sending the US into war.

In April 1917, Wilson went before Congress and asked Congress to declare war,
stating that it would make "`the world safe for democracy`".
In order to garner support for US involvement in the war, Wilson formed the Creel committee,
a group of "`Four Minute Men`" who gave propaganda speeches.

Leading the American Expeditionary Force into WWI
was General of the Armies **John "`Black Jack`" Pershing**.
Pershing had, as previously mentioned, been sent after Pancho Villa near the Mexican Border.

=== Paris Peace Conference

After the war, leaders from the world gathered in France to create terms of peace.
Among these were the "`Big Four`":
David Lloyd George (UK),
Georges Clemenceau (France),
Woodrow Wilson (USA),
and Vittorio Orlando (Italy).
Prior to the conference, Wilson created his Fourteen Points;
notably, the list contained the creation of a League of Nations to prevent this sort of thing from happening again.
David Lloyd George remarked on returning from the conference that it went
"`not bad, considering I was sitting between Jesus Christ [Wilson] and Napoleon [Clemenceau]`".
Notably, Ho Chi Minh (who will of course become important later)
went to the Peace Conference and made a case for civil rights for Vietnamese people,
but people didn't listen to him.

The **Treaty of Versailles** was drafted out of the Paris Peace Conference.
It was a fairly controversial treaty,
and it set up huge war reparations that Germany would have to pay.
China didn't want to sign because Shandong was transferred to Japan.
John Maynard Keynes wrote __The Economic Consequences of the Peace__,
discussing how it was a bad treaty.
Article 10 of the treaty specified the creation of the League of Nations.

Interestingly, Wilson was unable to get the treaty through Congress at home,
facing resistance from people like Henry Cabot Lodge against the League of Nations itself
(Wilson's brainchild).
